<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\HR\HRSetting;
use Illuminate\Support\Facades\DB;

class HRSettingsSeeder extends Seeder
{
    /**
     * Seed HR settings baseadas na legislação trabalhista Angolana 2025
     */
    public function run(): void
    {
        $tenantId = 1; // Ajustar conforme necessário

        $settings = [
            // HORÁRIO DE TRABALHO
            [
                'tenant_id' => $tenantId,
                'category' => 'worktime',
                'key' => 'working_days_per_month',
                'label' => 'Dias de Trabalho por Mês',
                'description' => 'Número médio de dias úteis de trabalho por mês',
                'value' => '22',
                'default_value' => '22',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:20|max:26',
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'worktime',
                'key' => 'working_hours_per_day',
                'label' => 'Horas de Trabalho por Dia',
                'description' => 'Carga horária diária normal de trabalho',
                'value' => '8',
                'default_value' => '8',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:6|max:10',
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'worktime',
                'key' => 'working_hours_per_week',
                'label' => 'Horas de Trabalho por Semana',
                'description' => 'Carga horária semanal normal de trabalho',
                'value' => '44',
                'default_value' => '44',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:40|max:48',
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'worktime',
                'key' => 'night_shift_start',
                'label' => 'Início do Turno Noturno',
                'description' => 'Horário de início do período noturno (formato 24h)',
                'value' => '22:00',
                'default_value' => '22:00',
                'value_type' => 'string',
                'validation_rules' => 'required|string',
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'worktime',
                'key' => 'night_shift_end',
                'label' => 'Fim do Turno Noturno',
                'description' => 'Horário de término do período noturno (formato 24h)',
                'value' => '06:00',
                'default_value' => '06:00',
                'value_type' => 'string',
                'validation_rules' => 'required|string',
                'is_active' => true,
                'display_order' => 5,
            ],

            [
                'tenant_id' => $tenantId,
                'category' => 'worktime',
                'key' => 'work_on_saturday',
                'label' => 'Trabalha ao Sábado',
                'description' => 'A empresa trabalha ao sábado? (1 = Sim, 0 = Não)',
                'value' => '0',
                'default_value' => '0',
                'value_type' => 'boolean',
                'validation_rules' => 'boolean',
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'worktime',
                'key' => 'saturday_working_hours',
                'label' => 'Horas de Trabalho ao Sábado',
                'description' => 'Carga horária do sábado (se aplicável). Ex: 4 = meio período, 8 = dia inteiro',
                'value' => '4',
                'default_value' => '4',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:1|max:8',
                'is_active' => true,
                'display_order' => 7,
            ],

            // HORAS EXTRAS - LEGISLAÇÃO ANGOLA
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_weekday_rate',
                'label' => 'Taxa Hora Extra - Dias Úteis',
                'description' => 'Percentual adicional para horas extras em dias úteis (Lei Angolana: 50%)',
                'value' => '50',
                'default_value' => '50',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:50|max:100',
                'is_active' => true,
                'display_order' => 10,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_weekend_rate',
                'label' => 'Taxa Hora Extra - Fins de Semana',
                'description' => 'Percentual adicional para horas extras aos fins de semana (Lei Angolana: 100%)',
                'value' => '100',
                'default_value' => '100',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:100|max:200',
                'is_active' => true,
                'display_order' => 11,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_holiday_rate',
                'label' => 'Taxa Hora Extra - Feriados',
                'description' => 'Percentual adicional para horas extras em feriados (Lei Angolana: 100%)',
                'value' => '100',
                'default_value' => '100',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:100|max:200',
                'is_active' => true,
                'display_order' => 12,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_night_rate',
                'label' => 'Taxa Trabalho Noturno',
                'description' => 'Percentual adicional para trabalho noturno (Lei Angolana: 25%)',
                'value' => '25',
                'default_value' => '25',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:25|max:50',
                'is_active' => true,
                'display_order' => 13,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_max_hours_day',
                'label' => 'Máximo de Horas Extras por Dia',
                'description' => 'Limite diário de horas extras permitidas',
                'value' => '4',
                'default_value' => '4',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:2|max:6',
                'is_active' => true,
                'display_order' => 14,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_max_hours_week',
                'label' => 'Máximo de Horas Extras por Semana',
                'description' => 'Limite semanal de horas extras permitidas',
                'value' => '12',
                'default_value' => '12',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:8|max:20',
                'is_active' => true,
                'display_order' => 15,
            ],

            // FÉRIAS - LEGISLAÇÃO ANGOLA
            [
                'tenant_id' => $tenantId,
                'category' => 'vacation',
                'key' => 'vacation_days_per_year',
                'label' => 'Dias de Férias por Ano',
                'description' => 'Dias úteis de férias por ano completo (Lei Angolana: 22 dias úteis)',
                'value' => '22',
                'default_value' => '22',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:22|max:30',
                'is_active' => true,
                'display_order' => 20,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'vacation',
                'key' => 'vacation_subsidy_rate',
                'label' => 'Taxa Subsídio de Férias (14º mês)',
                'description' => 'Percentual do salário para subsídio de férias (Lei Angolana: mínimo 50%)',
                'value' => '50',
                'default_value' => '50',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:50|max:100',
                'is_active' => true,
                'display_order' => 21,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'vacation',
                'key' => 'vacation_proportional',
                'label' => 'Férias Proporcionais',
                'description' => 'Calcular férias proporcionais aos meses trabalhados',
                'value' => '1',
                'default_value' => '1',
                'value_type' => 'boolean',
                'validation_rules' => 'boolean',
                'is_active' => true,
                'display_order' => 22,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'vacation',
                'key' => 'vacation_advance_days',
                'label' => 'Dias de Antecedência para Pagamento',
                'description' => 'Dias de antecedência para pagamento do subsídio de férias',
                'value' => '15',
                'default_value' => '15',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:7|max:30',
                'is_active' => true,
                'display_order' => 23,
            ],

            // LICENÇAS - LEGISLAÇÃO ANGOLA
            [
                'tenant_id' => $tenantId,
                'category' => 'leave',
                'key' => 'maternity_leave_days',
                'label' => 'Licença Maternidade (dias)',
                'description' => 'Dias de licença maternidade (Lei Angolana: 90 dias)',
                'value' => '90',
                'default_value' => '90',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:90|max:120',
                'is_active' => true,
                'display_order' => 30,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'leave',
                'key' => 'paternity_leave_days',
                'label' => 'Licença Paternidade (dias)',
                'description' => 'Dias de licença paternidade (Lei Angolana: 3 dias)',
                'value' => '3',
                'default_value' => '3',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:3|max:10',
                'is_active' => true,
                'display_order' => 31,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'leave',
                'key' => 'marriage_leave_days',
                'label' => 'Licença Casamento (dias)',
                'description' => 'Dias de licença para casamento (Lei Angolana: 10 dias)',
                'value' => '10',
                'default_value' => '10',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:5|max:15',
                'is_active' => true,
                'display_order' => 32,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'leave',
                'key' => 'bereavement_leave_days',
                'label' => 'Licença Luto Familiar (dias)',
                'description' => 'Dias de licença por falecimento de familiar direto (Lei Angolana: 5 dias)',
                'value' => '5',
                'default_value' => '5',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:3|max:10',
                'is_active' => true,
                'display_order' => 33,
            ],

            // ADIANTAMENTO SALARIAL
            [
                'tenant_id' => $tenantId,
                'category' => 'benefits',
                'key' => 'salary_advance_max_percentage',
                'label' => 'Percentual Máximo de Adiantamento',
                'description' => 'Percentual máximo do salário que pode ser adiantado (pode ser acima de 100%)',
                'value' => '50',
                'default_value' => '50',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:0|max:500',
                'is_active' => true,
                'display_order' => 39,
            ],

            // SUBSÍDIOS - LEGISLAÇÃO ANGOLA
            [
                'tenant_id' => $tenantId,
                'category' => 'benefits',
                'key' => 'allowance_calculation_method',
                'label' => 'Método de Cálculo de Subsídios',
                'description' => 'Como calcular subsídios (alimentação/transporte) na folha: proportional = proporcional aos dias trabalhados, full_if_worked = integral se trabalhou pelo menos 1 dia, daily_rate = valor fixo por dia trabalhado',
                'value' => 'proportional',
                'default_value' => 'proportional',
                'value_type' => 'string',
                'validation_rules' => 'required|string|in:proportional,full_if_worked,daily_rate',
                'is_active' => true,
                'display_order' => 40,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'benefits',
                'key' => 'monthly_food_allowance',
                'label' => 'Subsídio Alimentação Mensal (Kz)',
                'description' => 'Valor mensal base do subsídio de alimentação para todos os funcionários',
                'value' => '0',
                'default_value' => '0',
                'value_type' => 'decimal',
                'validation_rules' => 'required|numeric|min:0',
                'is_active' => true,
                'display_order' => 41,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'benefits',
                'key' => 'monthly_transport_allowance',
                'label' => 'Subsídio Transporte Mensal (Kz)',
                'description' => 'Valor mensal base do subsídio de transporte para todos os funcionários',
                'value' => '0',
                'default_value' => '0',
                'value_type' => 'decimal',
                'validation_rules' => 'required|numeric|min:0',
                'is_active' => true,
                'display_order' => 42,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'benefits',
                'key' => 'daily_meal_allowance',
                'label' => 'Subsídio Alimentação por Dia (Kz)',
                'description' => 'Valor fixo pago por dia trabalhado (usado se método = daily_rate)',
                'value' => '1000',
                'default_value' => '1000',
                'value_type' => 'decimal',
                'validation_rules' => 'required|numeric|min:0',
                'is_active' => true,
                'display_order' => 43,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'benefits',
                'key' => 'daily_transport_allowance',
                'label' => 'Subsídio Transporte por Dia (Kz)',
                'description' => 'Valor fixo pago por dia trabalhado (usado se método = daily_rate)',
                'value' => '1000',
                'default_value' => '1000',
                'value_type' => 'decimal',
                'validation_rules' => 'required|numeric|min:0',
                'is_active' => true,
                'display_order' => 44,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'benefits',
                'key' => 'christmas_bonus_rate',
                'label' => 'Subsídio de Natal',
                'description' => 'Percentual do salário para subsídio de Natal',
                'value' => '50',
                'default_value' => '50',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:0|max:200',
                'is_active' => true,
                'display_order' => 43,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'benefits',
                'key' => 'christmas_bonus_month',
                'label' => 'Mês de Pagamento do Subsídio de Natal',
                'description' => 'Mês para pagamento do subsídio de Natal',
                'value' => '12',
                'default_value' => '12',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:11|max:12',
                'is_active' => true,
                'display_order' => 44,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'benefits',
                'key' => 'meal_allowance_enabled',
                'label' => 'Subsídio de Alimentação Ativo',
                'description' => 'Habilitar subsídio de alimentação',
                'value' => '1',
                'default_value' => '1',
                'value_type' => 'boolean',
                'validation_rules' => 'boolean',
                'is_active' => true,
                'display_order' => 45,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'benefits',
                'key' => 'transport_allowance_enabled',
                'label' => 'Subsídio de Transporte Ativo',
                'description' => 'Habilitar subsídio de transporte',
                'value' => '1',
                'default_value' => '1',
                'value_type' => 'boolean',
                'validation_rules' => 'boolean',
                'is_active' => true,
                'display_order' => 46,
            ],

            // FOLHA DE PAGAMENTO
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'payroll_cutoff_day',
                'label' => 'Dia de Corte da Folha',
                'description' => 'Dia do mês para fechamento da folha de pagamento',
                'value' => '25',
                'default_value' => '25',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:1|max:28',
                'is_active' => true,
                'display_order' => 50,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'payroll_payment_day',
                'label' => 'Dia de Pagamento',
                'description' => 'Dia do mês para pagamento dos salários',
                'value' => '30',
                'default_value' => '30',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:1|max:31',
                'is_active' => true,
                'display_order' => 51,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'inss_employee_rate',
                'label' => 'Taxa INSS Funcionário',
                'description' => 'Percentual de desconto INSS sobre salário do funcionário',
                'value' => '3',
                'default_value' => '3',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:0|max:10',
                'is_active' => true,
                'display_order' => 52,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'inss_employer_rate',
                'label' => 'Taxa INSS Empresa',
                'description' => 'Percentual de contribuição INSS pela empresa',
                'value' => '8',
                'default_value' => '8',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:0|max:15',
                'is_active' => true,
                'display_order' => 53,
            ],

            // HORAS EXTRAS - MULTIPLIERS (doc Dembena §5.5)
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_first_hour_weekday',
                'label' => 'Multiplicador 1ª Hora Dia Útil',
                'description' => 'Multiplicador para a 1ª hora extra em dia útil (×1.25 = +25%)',
                'value' => '1.25',
                'default_value' => '1.25',
                'value_type' => 'decimal',
                'validation_rules' => 'required|numeric|min:1|max:3',
                'is_active' => true,
                'display_order' => 16,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_additional_hours_weekday',
                'label' => 'Multiplicador Horas Adicionais Dia Útil',
                'description' => 'Multiplicador para horas extras adicionais em dia útil (×1.375 = +37.5%)',
                'value' => '1.375',
                'default_value' => '1.375',
                'value_type' => 'decimal',
                'validation_rules' => 'required|numeric|min:1|max:3',
                'is_active' => true,
                'display_order' => 17,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_multiplier_weekend',
                'label' => 'Multiplicador Fim de Semana',
                'description' => 'Multiplicador horas extras fim de semana (×2.0 = +100%)',
                'value' => '2.0',
                'default_value' => '2.0',
                'value_type' => 'decimal',
                'validation_rules' => 'required|numeric|min:1|max:4',
                'is_active' => true,
                'display_order' => 18,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_multiplier_holiday',
                'label' => 'Multiplicador Feriado',
                'description' => 'Multiplicador horas extras feriado (×2.5 = +150%)',
                'value' => '2.5',
                'default_value' => '2.5',
                'value_type' => 'decimal',
                'validation_rules' => 'required|numeric|min:1|max:5',
                'is_active' => true,
                'display_order' => 19,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_daily_limit',
                'label' => 'Limite Diário Horas Extras',
                'description' => 'Máximo horas extras por dia (dias úteis)',
                'value' => '2',
                'default_value' => '2',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:1|max:6',
                'is_active' => true,
                'display_order' => 20,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_monthly_limit',
                'label' => 'Limite Mensal Horas Extras',
                'description' => 'Máximo horas extras por mês',
                'value' => '48',
                'default_value' => '48',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:20|max:100',
                'is_active' => true,
                'display_order' => 21,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_yearly_limit',
                'label' => 'Limite Anual Horas Extras',
                'description' => 'Máximo horas extras por ano',
                'value' => '200',
                'default_value' => '200',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:100|max:500',
                'is_active' => true,
                'display_order' => 22,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'night_shift_percentage',
                'label' => 'Adicional Noturno (%)',
                'description' => 'Percentual adicional para trabalho noturno (Art. 102º)',
                'value' => '25',
                'default_value' => '25',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:20|max:50',
                'is_active' => true,
                'display_order' => 23,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'night_shift_start_hour',
                'label' => 'Hora Início Turno Noturno',
                'description' => 'Hora de início do turno noturno (22 = 22:00)',
                'value' => '22',
                'default_value' => '22',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:18|max:23',
                'is_active' => true,
                'display_order' => 24,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'night_shift_end_hour',
                'label' => 'Hora Fim Turno Noturno',
                'description' => 'Hora de término do turno noturno (6 = 06:00)',
                'value' => '6',
                'default_value' => '6',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:4|max:8',
                'is_active' => true,
                'display_order' => 25,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'night_shift_multiplier',
                'label' => 'Multiplicador Turno Noturno',
                'description' => 'Multiplicador para turno noturno',
                'value' => '1.25',
                'default_value' => '1.25',
                'value_type' => 'decimal',
                'validation_rules' => 'required|numeric|min:1|max:2',
                'is_active' => true,
                'display_order' => 26,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'min_overtime_minutes',
                'label' => 'Mínimo Minutos para Hora Extra',
                'description' => 'Mínimo de minutos para contar como hora extra',
                'value' => '15',
                'default_value' => '15',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:5|max:30',
                'is_active' => true,
                'display_order' => 27,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'round_to_nearest_minutes',
                'label' => 'Arredondamento (minutos)',
                'description' => 'Arredondar horas extras para o intervalo mais próximo',
                'value' => '15',
                'default_value' => '15',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:5|max:30',
                'is_active' => true,
                'display_order' => 28,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'allow_partial_hours',
                'label' => 'Permitir Horas Parciais',
                'description' => 'Permitir registar horas fracionadas',
                'value' => '1',
                'default_value' => '1',
                'value_type' => 'boolean',
                'validation_rules' => 'boolean',
                'is_active' => true,
                'display_order' => 29,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'default_hourly_rate',
                'label' => 'Taxa Horária Padrão',
                'description' => 'Taxa horária padrão (fallback)',
                'value' => '10.00',
                'default_value' => '10.00',
                'value_type' => 'decimal',
                'validation_rules' => 'required|numeric|min:0',
                'is_active' => true,
                'display_order' => 30,
            ],

            // PAYROLL - TAX EXEMPTIONS (doc §11.2)
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'min_salary_tax_exempt',
                'label' => 'Salário Mínimo Isento IRT',
                'description' => 'Salário mínimo para isenção de IRT (AOA)',
                'value' => '70000',
                'default_value' => '70000',
                'value_type' => 'decimal',
                'validation_rules' => 'required|numeric|min:0',
                'is_active' => true,
                'display_order' => 54,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'transport_tax_exempt',
                'label' => 'Isenção Transporte IRT',
                'description' => 'Valor máximo de transporte isento de IRT (AOA)',
                'value' => '30000',
                'default_value' => '30000',
                'value_type' => 'decimal',
                'validation_rules' => 'required|numeric|min:0',
                'is_active' => true,
                'display_order' => 55,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'food_tax_exempt',
                'label' => 'Isenção Alimentação IRT',
                'description' => 'Valor máximo de alimentação isento de IRT (AOA)',
                'value' => '30000',
                'default_value' => '30000',
                'value_type' => 'decimal',
                'validation_rules' => 'required|numeric|min:0',
                'is_active' => true,
                'display_order' => 56,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'vacation_subsidy_percentage',
                'label' => 'Percentual Subsídio Férias',
                'description' => 'Percentual do salário base para subsídio de férias',
                'value' => '50',
                'default_value' => '50',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:0|max:100',
                'is_active' => true,
                'display_order' => 57,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'christmas_subsidy_percentage',
                'label' => 'Percentual Subsídio Natal',
                'description' => 'Percentual do salário base para subsídio de Natal',
                'value' => '50',
                'default_value' => '50',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:0|max:100',
                'is_active' => true,
                'display_order' => 58,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'monthly_working_days',
                'label' => 'Dias Úteis Mensais (Fallback)',
                'description' => 'Dias úteis mensais — fallback se contagem dinâmica retornar 0',
                'value' => '22',
                'default_value' => '22',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:20|max:26',
                'is_active' => true,
                'display_order' => 59,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'daily_work_hours',
                'label' => 'Horas Trabalho por Dia (Overtime)',
                'description' => 'Horas de trabalho diárias para cálculo de horas extras',
                'value' => '8',
                'default_value' => '8',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:6|max:12',
                'is_active' => true,
                'display_order' => 60,
            ],

            // GERAL
            [
                'tenant_id' => $tenantId,
                'category' => 'general',
                'key' => 'probation_period_days',
                'label' => 'Período de Experiência (dias)',
                'description' => 'Duração do período de experiência para novos funcionários',
                'value' => '90',
                'default_value' => '90',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:30|max:180',
                'is_active' => true,
                'display_order' => 60,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'general',
                'key' => 'termination_notice_days',
                'label' => 'Aviso Prévio (dias)',
                'description' => 'Dias de aviso prévio para rescisão de contrato',
                'value' => '30',
                'default_value' => '30',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:15|max:60',
                'is_active' => true,
                'display_order' => 61,
            ],
        ];

        foreach ($settings as $setting) {
            HRSetting::updateOrCreate(
                [
                    'tenant_id' => $setting['tenant_id'],
                    'key' => $setting['key'],
                ],
                $setting
            );
        }

        $this->command->info('✓ Configurações de RH (Angola 2025) criadas com sucesso!');
    }
}
