<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\HR\HRSetting;
use Illuminate\Support\Facades\DB;

class HRSettingsSeeder extends Seeder
{
    /**
     * Seed HR settings baseadas na legislação trabalhista Angolana 2025
     */
    public function run(): void
    {
        $tenantId = 1; // Ajustar conforme necessário

        $settings = [
            // HORÁRIO DE TRABALHO
            [
                'tenant_id' => $tenantId,
                'category' => 'worktime',
                'key' => 'working_days_per_month',
                'label' => 'Dias de Trabalho por Mês',
                'description' => 'Número médio de dias úteis de trabalho por mês',
                'value' => '22',
                'default_value' => '22',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:20|max:26',
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'worktime',
                'key' => 'working_hours_per_day',
                'label' => 'Horas de Trabalho por Dia',
                'description' => 'Carga horária diária normal de trabalho',
                'value' => '8',
                'default_value' => '8',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:6|max:10',
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'worktime',
                'key' => 'working_hours_per_week',
                'label' => 'Horas de Trabalho por Semana',
                'description' => 'Carga horária semanal normal de trabalho',
                'value' => '44',
                'default_value' => '44',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:40|max:48',
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'worktime',
                'key' => 'night_shift_start',
                'label' => 'Início do Turno Noturno',
                'description' => 'Horário de início do período noturno (formato 24h)',
                'value' => '22:00',
                'default_value' => '22:00',
                'value_type' => 'string',
                'validation_rules' => 'required|string',
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'worktime',
                'key' => 'night_shift_end',
                'label' => 'Fim do Turno Noturno',
                'description' => 'Horário de término do período noturno (formato 24h)',
                'value' => '06:00',
                'default_value' => '06:00',
                'value_type' => 'string',
                'validation_rules' => 'required|string',
                'is_active' => true,
                'display_order' => 5,
            ],

            // HORAS EXTRAS - LEGISLAÇÃO ANGOLA
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_weekday_rate',
                'label' => 'Taxa Hora Extra - Dias Úteis',
                'description' => 'Percentual adicional para horas extras em dias úteis (Lei Angolana: 50%)',
                'value' => '50',
                'default_value' => '50',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:50|max:100',
                'is_active' => true,
                'display_order' => 10,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_weekend_rate',
                'label' => 'Taxa Hora Extra - Fins de Semana',
                'description' => 'Percentual adicional para horas extras aos fins de semana (Lei Angolana: 100%)',
                'value' => '100',
                'default_value' => '100',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:100|max:200',
                'is_active' => true,
                'display_order' => 11,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_holiday_rate',
                'label' => 'Taxa Hora Extra - Feriados',
                'description' => 'Percentual adicional para horas extras em feriados (Lei Angolana: 100%)',
                'value' => '100',
                'default_value' => '100',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:100|max:200',
                'is_active' => true,
                'display_order' => 12,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_night_rate',
                'label' => 'Taxa Trabalho Noturno',
                'description' => 'Percentual adicional para trabalho noturno (Lei Angolana: 25%)',
                'value' => '25',
                'default_value' => '25',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:25|max:50',
                'is_active' => true,
                'display_order' => 13,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_max_hours_day',
                'label' => 'Máximo de Horas Extras por Dia',
                'description' => 'Limite diário de horas extras permitidas',
                'value' => '4',
                'default_value' => '4',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:2|max:6',
                'is_active' => true,
                'display_order' => 14,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'overtime',
                'key' => 'overtime_max_hours_week',
                'label' => 'Máximo de Horas Extras por Semana',
                'description' => 'Limite semanal de horas extras permitidas',
                'value' => '12',
                'default_value' => '12',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:8|max:20',
                'is_active' => true,
                'display_order' => 15,
            ],

            // FÉRIAS - LEGISLAÇÃO ANGOLA
            [
                'tenant_id' => $tenantId,
                'category' => 'vacation',
                'key' => 'vacation_days_per_year',
                'label' => 'Dias de Férias por Ano',
                'description' => 'Dias úteis de férias por ano completo (Lei Angolana: 22 dias úteis)',
                'value' => '22',
                'default_value' => '22',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:22|max:30',
                'is_active' => true,
                'display_order' => 20,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'vacation',
                'key' => 'vacation_subsidy_rate',
                'label' => 'Taxa Subsídio de Férias (14º mês)',
                'description' => 'Percentual do salário para subsídio de férias (Lei Angolana: mínimo 50%)',
                'value' => '50',
                'default_value' => '50',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:50|max:100',
                'is_active' => true,
                'display_order' => 21,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'vacation',
                'key' => 'vacation_proportional',
                'label' => 'Férias Proporcionais',
                'description' => 'Calcular férias proporcionais aos meses trabalhados',
                'value' => '1',
                'default_value' => '1',
                'value_type' => 'boolean',
                'validation_rules' => 'boolean',
                'is_active' => true,
                'display_order' => 22,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'vacation',
                'key' => 'vacation_advance_days',
                'label' => 'Dias de Antecedência para Pagamento',
                'description' => 'Dias de antecedência para pagamento do subsídio de férias',
                'value' => '15',
                'default_value' => '15',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:7|max:30',
                'is_active' => true,
                'display_order' => 23,
            ],

            // LICENÇAS - LEGISLAÇÃO ANGOLA
            [
                'tenant_id' => $tenantId,
                'category' => 'leave',
                'key' => 'maternity_leave_days',
                'label' => 'Licença Maternidade (dias)',
                'description' => 'Dias de licença maternidade (Lei Angolana: 90 dias)',
                'value' => '90',
                'default_value' => '90',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:90|max:120',
                'is_active' => true,
                'display_order' => 30,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'leave',
                'key' => 'paternity_leave_days',
                'label' => 'Licença Paternidade (dias)',
                'description' => 'Dias de licença paternidade (Lei Angolana: 3 dias)',
                'value' => '3',
                'default_value' => '3',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:3|max:10',
                'is_active' => true,
                'display_order' => 31,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'leave',
                'key' => 'marriage_leave_days',
                'label' => 'Licença Casamento (dias)',
                'description' => 'Dias de licença para casamento (Lei Angolana: 10 dias)',
                'value' => '10',
                'default_value' => '10',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:5|max:15',
                'is_active' => true,
                'display_order' => 32,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'leave',
                'key' => 'bereavement_leave_days',
                'label' => 'Licença Luto Familiar (dias)',
                'description' => 'Dias de licença por falecimento de familiar direto (Lei Angolana: 5 dias)',
                'value' => '5',
                'default_value' => '5',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:3|max:10',
                'is_active' => true,
                'display_order' => 33,
            ],

            // SUBSÍDIOS - LEGISLAÇÃO ANGOLA
            [
                'tenant_id' => $tenantId,
                'category' => 'benefits',
                'key' => 'christmas_bonus_rate',
                'label' => 'Subsídio de Natal (13º mês)',
                'description' => 'Percentual do salário para subsídio de Natal (Lei Angolana: 100%)',
                'value' => '100',
                'default_value' => '100',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:100|max:100',
                'is_active' => true,
                'display_order' => 40,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'benefits',
                'key' => 'christmas_bonus_month',
                'label' => 'Mês de Pagamento do 13º',
                'description' => 'Mês para pagamento do subsídio de Natal',
                'value' => '12',
                'default_value' => '12',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:11|max:12',
                'is_active' => true,
                'display_order' => 41,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'benefits',
                'key' => 'meal_allowance_enabled',
                'label' => 'Subsídio de Alimentação Ativo',
                'description' => 'Habilitar subsídio de alimentação',
                'value' => '1',
                'default_value' => '1',
                'value_type' => 'boolean',
                'validation_rules' => 'boolean',
                'is_active' => true,
                'display_order' => 42,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'benefits',
                'key' => 'transport_allowance_enabled',
                'label' => 'Subsídio de Transporte Ativo',
                'description' => 'Habilitar subsídio de transporte',
                'value' => '1',
                'default_value' => '1',
                'value_type' => 'boolean',
                'validation_rules' => 'boolean',
                'is_active' => true,
                'display_order' => 43,
            ],

            // FOLHA DE PAGAMENTO
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'payroll_cutoff_day',
                'label' => 'Dia de Corte da Folha',
                'description' => 'Dia do mês para fechamento da folha de pagamento',
                'value' => '25',
                'default_value' => '25',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:1|max:28',
                'is_active' => true,
                'display_order' => 50,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'payroll_payment_day',
                'label' => 'Dia de Pagamento',
                'description' => 'Dia do mês para pagamento dos salários',
                'value' => '30',
                'default_value' => '30',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:1|max:31',
                'is_active' => true,
                'display_order' => 51,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'inss_employee_rate',
                'label' => 'Taxa INSS Funcionário',
                'description' => 'Percentual de desconto INSS sobre salário do funcionário',
                'value' => '3',
                'default_value' => '3',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:0|max:10',
                'is_active' => true,
                'display_order' => 52,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'payroll',
                'key' => 'inss_employer_rate',
                'label' => 'Taxa INSS Empresa',
                'description' => 'Percentual de contribuição INSS pela empresa',
                'value' => '8',
                'default_value' => '8',
                'value_type' => 'percentage',
                'validation_rules' => 'required|numeric|min:0|max:15',
                'is_active' => true,
                'display_order' => 53,
            ],

            // GERAL
            [
                'tenant_id' => $tenantId,
                'category' => 'general',
                'key' => 'probation_period_days',
                'label' => 'Período de Experiência (dias)',
                'description' => 'Duração do período de experiência para novos funcionários',
                'value' => '90',
                'default_value' => '90',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:30|max:180',
                'is_active' => true,
                'display_order' => 60,
            ],
            [
                'tenant_id' => $tenantId,
                'category' => 'general',
                'key' => 'termination_notice_days',
                'label' => 'Aviso Prévio (dias)',
                'description' => 'Dias de aviso prévio para rescisão de contrato',
                'value' => '30',
                'default_value' => '30',
                'value_type' => 'integer',
                'validation_rules' => 'required|integer|min:15|max:60',
                'is_active' => true,
                'display_order' => 61,
            ],
        ];

        foreach ($settings as $setting) {
            HRSetting::updateOrCreate(
                [
                    'tenant_id' => $setting['tenant_id'],
                    'key' => $setting['key'],
                ],
                $setting
            );
        }

        $this->command->info('✓ Configurações de RH (Angola 2025) criadas com sucesso!');
    }
}
