<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Models\Product;use App\Models\Restaurant\DiningTable;use App\Models\Restaurant\KitchenStation;use App\Models\Restaurant\Order;use App\Models\Restaurant\OrderItem;use App\Models\Restaurant\Venue;use App\Services\Restaurant\RestaurantCheckoutService;use App\Services\Restaurant\RestaurantOrderService;use Illuminate\Http\Request;
class RestaurantController extends Controller {
 public function snapshot(){ $t=activeTenantId();return response()->json(['venues'=>Venue::withoutGlobalScopes()->where('tenant_id',$t)->where('is_active',true)->with('areas')->get(),'tables'=>DiningTable::withoutGlobalScopes()->where('tenant_id',$t)->where('is_active',true)->get(),'stations'=>KitchenStation::withoutGlobalScopes()->where('tenant_id',$t)->where('is_active',true)->get(),'products'=>Product::where('tenant_id',$t)->where('is_active',true)->select('id','category_id','code','name','price','unit','updated_at')->get(),'orders'=>Order::withoutGlobalScopes()->with('items')->where('tenant_id',$t)->open()->get(),'server_time'=>now()->toIso8601String()]);}
 public function open(Request $r,RestaurantOrderService $s){$d=$r->validate(['venue_id'=>'required|integer','table_id'=>'nullable|integer','channel'=>'nullable|in:table,counter,takeaway,delivery','guest_count'=>'nullable|integer|min:1','local_uuid'=>'required|uuid','notes'=>'nullable|string']);return response()->json($s->open($d,activeTenantId(),auth()->id())->load('items'),201);}
 public function add(Request $r,int $order,RestaurantOrderService $s){$d=$r->validate(['product_id'=>'required|integer','quantity'=>'required|numeric|min:.001','notes'=>'nullable|string|max:500']);$o=Order::withoutGlobalScopes()->where('tenant_id',activeTenantId())->findOrFail($order);return response()->json($s->addItem($o,$d['product_id'],$d['quantity'],$d['notes']??null,activeTenantId(),auth()->id()),201);}
 public function confirm(int $order,RestaurantOrderService $s){$o=Order::withoutGlobalScopes()->where('tenant_id',activeTenantId())->findOrFail($order);return response()->json($s->confirm($o,activeTenantId(),auth()->id()));}
 public function checkout(Request $r,int $order,RestaurantCheckoutService $s){$d=$r->validate(['idempotency_key'=>'required|uuid','document_type'=>'required|in:FR,FT','client_id'=>'nullable|integer','item_ids'=>'nullable|array','item_ids.*'=>'integer','payment_method_id'=>'nullable|integer','payments'=>'nullable|array','payments.*.payment_method_id'=>'required_with:payments|integer','payments.*.amount'=>'required_with:payments|numeric|min:.01']);$o=Order::withoutGlobalScopes()->where('tenant_id',activeTenantId())->findOrFail($order);return response()->json($s->checkout($o,$d,activeTenantId(),auth()->id())->load('items'),201);}
 public function transfer(Request $r,int $order,RestaurantOrderService $s){$d=$r->validate(['table_id'=>'required|integer']);$o=Order::withoutGlobalScopes()->where('tenant_id',activeTenantId())->findOrFail($order);return response()->json($s->transfer($o,$d['table_id'],activeTenantId(),auth()->id()));}
 public function merge(Request $r,int $order,RestaurantOrderService $s){$d=$r->validate(['target_order_id'=>'required|integer']);$source=Order::withoutGlobalScopes()->where('tenant_id',activeTenantId())->findOrFail($order);$target=Order::withoutGlobalScopes()->where('tenant_id',activeTenantId())->findOrFail($d['target_order_id']);return response()->json($s->merge($source,$target,activeTenantId(),auth()->id()));}
 public function voidItem(Request $r,int $order,int $item,RestaurantOrderService $s){$d=$r->validate(['reason'=>'required|string|min:3|max:500']);$record=OrderItem::withoutGlobalScopes()->where('tenant_id',activeTenantId())->where('order_id',$order)->findOrFail($item);$s->voidProducedItem($record,$d['reason'],activeTenantId(),auth()->id());return response()->json(['ok'=>true]);}
}
