import 'package:flutter/material.dart';

/// Item de menu de um módulo. [route] não-nulo abre ecrã nativo;
/// caso contrário abre o placeholder com o nome do item.
class MenuEntry {
  final String label;
  final IconData icon;
  final String? route;
  const MenuEntry(this.label, this.icon, [this.route]);
}

/// Submenus por módulo — espelham o sidebar do website (layouts/app.blade.php).
const Map<String, List<MenuEntry>> kModuleMenus = {
  'invoicing': [
    MenuEntry('Dashboard', Icons.dashboard_outlined, 'invoicing-dashboard'),
    MenuEntry('POS — Ponto de Venda', Icons.point_of_sale, 'pos'),
    MenuEntry('Turnos de Caixa', Icons.access_time, 'list:shifts'),
    MenuEntry('Histórico de Turnos', Icons.history, 'list:shifts'),
    MenuEntry('Relatórios POS', Icons.bar_chart, 'invoicing-dashboard'),
    MenuEntry('Clientes', Icons.people, 'clients'),
    MenuEntry('Fornecedores', Icons.local_shipping, 'list:suppliers'),
    MenuEntry('Produtos', Icons.inventory_2, 'catalog'),
    MenuEntry('Categorias', Icons.category, 'list:categories'),
    MenuEntry('Marcas', Icons.sell, 'list:brands'),
    MenuEntry('Proformas de Venda', Icons.description, 'list:sales-proformas'),
    MenuEntry('Faturas de Venda', Icons.receipt_long, 'list:sales-invoices'),
    MenuEntry('Proformas de Compra', Icons.description_outlined, 'list:purchase-proformas'),
    MenuEntry('Faturas de Compra', Icons.receipt, 'list:purchase-invoices'),
    MenuEntry('Recibos', Icons.payments, 'list:receipts'),
    MenuEntry('Notas de Crédito', Icons.undo, 'list:credit-notes'),
    MenuEntry('Notas de Débito', Icons.redo, 'list:debit-notes'),
    MenuEntry('Adiantamentos', Icons.savings, 'list:advances'),
    MenuEntry('Armazéns', Icons.warehouse, 'list:warehouses'),
    MenuEntry('Lotes e Validades', Icons.event_available, 'list:product-batches'),
    MenuEntry('Impostos (IVA)', Icons.percent, 'list:taxes'),
    MenuEntry('Séries de Documentos', Icons.tag, 'list:series'),
    MenuEntry('Gerador SAFT-AO', Icons.file_download),
    MenuEntry('AGT Angola', Icons.verified),
    MenuEntry('Configurações', Icons.settings),
  ],
  'treasury': [
    MenuEntry('Relatórios', Icons.bar_chart),
    MenuEntry('Contas Bancárias', Icons.account_balance),
    MenuEntry('Transações', Icons.swap_horiz),
    MenuEntry('Transferências', Icons.sync_alt),
    MenuEntry('Métodos de Pagamento', Icons.credit_card),
    MenuEntry('Bancos', Icons.account_balance_outlined),
    MenuEntry('Caixas', Icons.point_of_sale),
  ],
  'rh': [
    MenuEntry('Dashboard', Icons.dashboard_outlined),
    MenuEntry('Funcionários', Icons.badge),
    MenuEntry('Departamentos', Icons.apartment),
    MenuEntry('Cargos', Icons.work_outline),
    MenuEntry('Presenças', Icons.fact_check),
    MenuEntry('Férias', Icons.beach_access),
    MenuEntry('Licenças e Faltas', Icons.event_busy),
    MenuEntry('Horas Extras', Icons.more_time),
    MenuEntry('Turno Noturno', Icons.nightlight),
    MenuEntry('Descontos Salariais', Icons.money_off),
    MenuEntry('Turnos', Icons.schedule),
    MenuEntry('Folha de Pagamento', Icons.receipt_long),
    MenuEntry('Adiantamentos', Icons.savings),
    MenuEntry('Relatórios', Icons.bar_chart),
    MenuEntry('Configurações RH', Icons.settings),
  ],
  'contabilidade': [
    MenuEntry('Dashboard', Icons.dashboard_outlined),
    MenuEntry('Plano de Contas', Icons.account_tree),
    MenuEntry('Diários', Icons.menu_book),
    MenuEntry('Tipos de Documentos', Icons.description),
    MenuEntry('Lançamentos', Icons.edit_note),
    MenuEntry('Períodos', Icons.calendar_month),
    MenuEntry('Relatórios', Icons.bar_chart),
    MenuEntry('Reconciliação', Icons.rule),
    MenuEntry('Imobilizado', Icons.chair),
    MenuEntry('Moedas', Icons.currency_exchange),
    MenuEntry('Centros de Custo', Icons.hub),
    MenuEntry('Analítica', Icons.analytics),
    MenuEntry('Orçamentos', Icons.request_quote),
    MenuEntry('Configurações', Icons.settings),
  ],
  'oficina': [
    MenuEntry('Dashboard', Icons.dashboard_outlined),
    MenuEntry('Veículos', Icons.directions_car),
    MenuEntry('Mecânicos', Icons.engineering),
    MenuEntry('Serviços', Icons.build),
    MenuEntry('Peças', Icons.settings_input_component),
    MenuEntry('Ordens de Serviço', Icons.assignment),
    MenuEntry('Relatórios', Icons.bar_chart),
  ],
  'hotel': [
    MenuEntry('Dashboard', Icons.dashboard_outlined),
    MenuEntry('Reservas', Icons.book_online),
    MenuEntry('Walk-in', Icons.login),
    MenuEntry('Check-out', Icons.logout),
    MenuEntry('Calendário', Icons.calendar_month),
    MenuEntry('Housekeeping', Icons.cleaning_services),
    MenuEntry('Manutenção', Icons.handyman),
    MenuEntry('Funcionários', Icons.badge),
    MenuEntry('Quartos', Icons.meeting_room),
    MenuEntry('Tipos de Quarto', Icons.bed),
    MenuEntry('Hóspedes', Icons.people),
    MenuEntry('Tarifas', Icons.price_change),
    MenuEntry('Pacotes', Icons.card_giftcard),
    MenuEntry('Relatórios', Icons.bar_chart),
    MenuEntry('Configurações', Icons.settings),
  ],
  'salon': [
    MenuEntry('Dashboard', Icons.dashboard_outlined),
    MenuEntry('Agendamentos', Icons.event),
    MenuEntry('Clientes', Icons.people),
    MenuEntry('Serviços', Icons.content_cut),
    MenuEntry('Profissionais', Icons.badge),
    MenuEntry('Produtos', Icons.inventory_2),
    MenuEntry('POS / Faturar', Icons.point_of_sale),
    MenuEntry('Relatórios', Icons.bar_chart),
    MenuEntry('Configurações', Icons.settings),
  ],
  'eventos': [
    MenuEntry('Dashboard', Icons.dashboard_outlined),
    MenuEntry('Calendário', Icons.calendar_month),
    MenuEntry('Equipamentos', Icons.speaker),
    MenuEntry('Locais', Icons.place),
    MenuEntry('Tipos de Eventos', Icons.category),
    MenuEntry('Técnicos', Icons.engineering),
    MenuEntry('Relatórios', Icons.bar_chart),
  ],
  'crm': [
    MenuEntry('Dashboard', Icons.dashboard_outlined),
    MenuEntry('Leads', Icons.person_search),
    MenuEntry('Oportunidades', Icons.trending_up),
    MenuEntry('Funil de Vendas', Icons.filter_alt),
  ],
  'inventario': [
    MenuEntry('Dashboard', Icons.dashboard_outlined),
    MenuEntry('Armazéns', Icons.warehouse),
    MenuEntry('Movimentos', Icons.swap_vert),
    MenuEntry('Contagem de Stock', Icons.checklist),
  ],
  'compras': [
    MenuEntry('Dashboard', Icons.dashboard_outlined),
    MenuEntry('Fornecedores', Icons.local_shipping),
    MenuEntry('Requisições', Icons.assignment),
    MenuEntry('Encomendas', Icons.shopping_cart),
  ],
  'projetos': [
    MenuEntry('Dashboard', Icons.dashboard_outlined),
    MenuEntry('Projetos', Icons.work),
    MenuEntry('Tarefas', Icons.task_alt),
    MenuEntry('Timesheet', Icons.timer),
  ],
};
