<div class="min-h-screen bg-slate-100 p-3 sm:p-5"><div class="mx-auto max-w-6xl space-y-5">
<header><a href="{{route('restaurant.dashboard')}}" class="font-bold text-orange-600">← Restaurante</a><div class="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 class="text-3xl font-black text-slate-900">Clientes e fornecedores</h1><p class="text-slate-500">Cadastro único partilhado com a Faturação, compras e documentos fiscais.</p></div><div class="flex gap-2"><button wire:click="create('clients')" class="rounded-xl bg-blue-600 px-4 py-3 font-black text-white"><i class="fas fa-user-plus mr-2"></i>Novo cliente</button><button wire:click="create('suppliers')" class="rounded-xl bg-orange-600 px-4 py-3 font-black text-white"><i class="fas fa-truck mr-2"></i>Novo fornecedor</button></div></div></header>
<div class="flex gap-2 rounded-2xl bg-white p-2 shadow"><button wire:click="$set('tab','clients')" class="flex-1 rounded-xl p-3 font-black {{$tab==='clients'?'bg-blue-600 text-white':'text-slate-600'}}">Clientes ({{$clients->count()}})</button><button wire:click="$set('tab','suppliers')" class="flex-1 rounded-xl p-3 font-black {{$tab==='suppliers'?'bg-orange-600 text-white':'text-slate-600'}}">Fornecedores ({{$suppliers->count()}})</button></div>
<section class="overflow-hidden rounded-3xl bg-white shadow"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Nome</th><th class="p-4">NIF</th><th class="p-4">Contacto</th><th class="p-4">Tipo</th></tr></thead><tbody class="divide-y">@foreach($tab==='clients'?$clients:$suppliers as $contact)<tr><td class="p-4 font-black text-slate-900">{{$contact->name}}</td><td class="p-4">{{$contact->nif}}</td><td class="p-4">{{$contact->phone ?: $contact->email ?: '—'}}</td><td class="p-4">{{$contact->type==='pessoa_juridica'?'Empresa':'Particular'}}</td></tr>@endforeach</tbody></table></div></section>
@if($showForm)<div class="fixed inset-0 z-[110] grid place-items-center bg-slate-950/75 p-3 backdrop-blur-sm"><form wire:submit="save" class="max-h-[95vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white shadow-2xl"><div class="sticky top-0 z-10 flex justify-between border-b border-slate-200 bg-white p-5 sm:p-6"><div><p class="text-xs font-black uppercase tracking-wider text-orange-600">Cadastro integrado com a Faturação</p><h2 class="text-2xl font-black text-slate-950">Novo {{$tab==='suppliers'?'fornecedor':'cliente'}}</h2><p class="mt-1 text-sm text-slate-500">Os campos fiscais serão usados nas faturas, SAF-T e compras.</p></div><button type="button" wire:click="$set('showForm',false)" class="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-slate-200 bg-slate-100 text-xl font-black text-slate-700">×</button></div>
<div class="p-5 sm:p-6"><div class="grid gap-4 sm:grid-cols-2">
<label class="font-bold text-slate-800 sm:col-span-2">Nome / Designação social <span class="text-red-500">*</span><input wire:model="name" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950 shadow-sm outline-none placeholder:text-slate-400 focus:border-blue-600 focus:ring-2 focus:ring-blue-100" placeholder="Nome completo ou nome da empresa"></label>
<label class="font-bold text-slate-800">Tipo de entidade <span class="text-red-500">*</span><select wire:model="type" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950 focus:border-blue-600 focus:ring-blue-100"><option value="pessoa_fisica">Pessoa física / Particular</option><option value="pessoa_juridica">Pessoa jurídica / Empresa</option></select></label>
<label class="font-bold text-slate-800">NIF {{$tab==='suppliers'?'':'*'}}<input wire:model="nif" inputmode="numeric" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950 focus:border-blue-600 focus:ring-blue-100" placeholder="Ex.: 5001234567"><span class="mt-1 block text-xs font-normal text-slate-500">Angola: 9–10 dígitos; começa por 2, 3 ou 5.</span></label>
<label class="font-bold text-slate-800">País <span class="text-red-500">*</span><select wire:model.live="country" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950 focus:border-blue-600 focus:ring-blue-100">@foreach($countries as $code=>$label)<option value="{{$code}}">{{$label}} ({{$code}})</option>@endforeach</select></label>
<label class="font-bold text-slate-800">Província / Estado
@if($country==='AO')<select wire:model="province" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950 focus:border-blue-600"><option value="">Selecione</option>@foreach($provinces as $provinceName)<option value="{{$provinceName}}">{{$provinceName}}</option>@endforeach</select>@else<input wire:model="province" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950" placeholder="Província ou estado">@endif</label>
<label class="font-bold text-slate-800">Cidade<input wire:model="city" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950" placeholder="Cidade"></label><label class="font-bold text-slate-800">Código postal<input wire:model="postalCode" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950" placeholder="Opcional"></label>
<label class="font-bold text-slate-800">Telefone<input wire:model="phone" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950" placeholder="+244 9XX XXX XXX"></label><label class="font-bold text-slate-800">Telemóvel alternativo<input wire:model="mobile" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950"></label>
<label class="font-bold text-slate-800 sm:col-span-2">Email<input type="email" wire:model="email" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950" placeholder="email@empresa.ao"></label><label class="font-bold text-slate-800 sm:col-span-2">Endereço<input wire:model="address" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950" placeholder="Rua, bairro, edifício"></label>
<label class="font-bold text-slate-800">Regime fiscal<select wire:model="taxRegime" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950"><option value="geral">Regime Geral</option><option value="simplificado">Regime Simplificado</option><option value="isento">Isento / Não sujeito</option></select></label><label class="flex items-center justify-between rounded-xl border-2 border-slate-200 bg-slate-50 p-4 font-bold text-slate-800">Sujeito a IVA<input type="checkbox" wire:model="isIvaSubject" class="h-5 w-5 rounded border-slate-400 text-blue-600"></label>
<label class="font-bold text-slate-800">Limite de crédito (Kz)<input type="number" min="0" step=".01" wire:model="creditLimit" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950"></label><label class="font-bold text-slate-800">Prazo de pagamento (dias)<input type="number" min="0" wire:model="paymentTermDays" class="mt-1.5 w-full rounded-xl border-2 border-slate-300 bg-white px-4 py-3 text-slate-950"></label>
</div>@if($errors->any())<div class="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700"><i class="fas fa-circle-exclamation mr-2"></i>{{$errors->first()}}</div>@endif<button class="mt-5 w-full rounded-2xl bg-gradient-to-r from-emerald-600 to-teal-600 p-4 text-lg font-black text-white shadow-lg hover:from-emerald-700 hover:to-teal-700"><i class="fas fa-floppy-disk mr-2"></i>Guardar e disponibilizar</button></div></form></div>@endif
</div></div>
