<div class="min-h-screen bg-slate-50 p-3 sm:p-5 lg:p-6">
    <div class="mx-auto max-w-[1500px]">
        <header class="overflow-hidden rounded-3xl bg-slate-950 shadow-xl">
            <div class="relative px-5 py-6 sm:px-7 sm:py-8">
                <div class="absolute inset-y-0 right-0 hidden w-2/5 bg-gradient-to-l from-orange-500/25 to-transparent lg:block"></div>
                <div class="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between">
                    <div>
                        <a href="{{route('restaurant.dashboard')}}" class="inline-flex items-center gap-2 text-sm font-bold text-orange-300 transition hover:text-orange-200"><i class="fas fa-arrow-left"></i>Restaurante</a>
                        <div class="mt-4 flex items-center gap-3"><span class="grid h-12 w-12 place-items-center rounded-2xl bg-orange-500 text-xl text-white shadow-lg shadow-orange-950/40"><i class="fas fa-book-open"></i></span><div><h1 class="text-2xl font-black tracking-tight text-white sm:text-3xl">Fichas técnicas</h1><p class="mt-1 text-sm text-slate-400">Receitas, rendimento, custo e desperdício por produto.</p></div></div>
                    </div>
                    <button wire:click="create" class="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-orange-500 px-5 py-3 font-black text-white shadow-lg shadow-orange-950/30 transition hover:-translate-y-0.5 hover:bg-orange-400 focus:outline-none focus:ring-4 focus:ring-orange-300/40"><i class="fas fa-plus"></i>Nova ficha técnica</button>
                </div>
            </div>
        </header>

        <section class="mt-5 grid grid-cols-3 gap-3 sm:gap-4">
            @foreach([['Fichas',$stats['total'],'fa-book-open','bg-orange-50 text-orange-600'],['Ativas',$stats['active'],'fa-circle-check','bg-emerald-50 text-emerald-600'],['Ingredientes',$stats['ingredients'],'fa-carrot','bg-violet-50 text-violet-600']] as $stat)
                <article class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div class="flex items-center gap-3"><span class="hidden h-10 w-10 place-items-center rounded-xl sm:grid {{$stat[3]}}"><i class="fas {{$stat[2]}}"></i></span><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">{{$stat[0]}}</p><strong class="text-2xl font-black text-slate-900">{{$stat[1]}}</strong></div></div></article>
            @endforeach
        </section>

        <section class="mt-5 rounded-3xl border border-slate-200 bg-white shadow-sm">
            <div class="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5">
                <div class="relative min-w-0 flex-1 sm:max-w-xl"><i class="fas fa-search absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"></i><input wire:model.live.debounce.300ms="search" class="w-full rounded-2xl border-slate-200 bg-slate-50 py-3 pl-11 pr-4 text-sm font-semibold placeholder:text-slate-400 focus:border-orange-400 focus:bg-white focus:ring-orange-200" placeholder="Pesquisar prato ou código..."></div>
                <div class="flex items-center justify-between gap-3"><p class="text-sm font-semibold text-slate-500">{{$recipes->count()}} resultado(s)</p><div class="inline-flex rounded-xl bg-slate-100 p-1" aria-label="Modo de visualização"><button wire:click="setView('grid')" class="grid h-9 w-10 place-items-center rounded-lg transition {{$viewMode==='grid'?'bg-white text-orange-600 shadow-sm':'text-slate-500 hover:text-slate-800'}}" aria-label="Ver em grelha" title="Grelha"><i class="fas fa-grip"></i></button><button wire:click="setView('list')" class="grid h-9 w-10 place-items-center rounded-lg transition {{$viewMode==='list'?'bg-white text-orange-600 shadow-sm':'text-slate-500 hover:text-slate-800'}}" aria-label="Ver em lista" title="Lista"><i class="fas fa-list"></i></button></div></div>
            </div>

            @if($recipes->isEmpty())
                <div class="grid min-h-96 place-items-center px-6 py-14 text-center"><div><span class="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-orange-50 text-3xl text-orange-500"><i class="fas fa-book-open"></i></span><h2 class="mt-5 text-xl font-black text-slate-900">{{$search ? 'Nenhuma ficha encontrada' : 'Ainda não existem fichas técnicas'}}</h2><p class="mx-auto mt-2 max-w-md text-sm text-slate-500">{{$search ? 'Altere a pesquisa para encontrar outro prato.' : 'Crie a primeira receita para controlar ingredientes, rendimento e consumo de stock.'}}</p>@if(!$search)<button wire:click="create" class="mt-5 rounded-xl bg-orange-500 px-5 py-3 font-black text-white">Criar primeira ficha</button>@endif</div></div>
            @elseif($viewMode === 'grid')
                <div class="grid gap-4 p-4 sm:grid-cols-2 sm:p-5 xl:grid-cols-3">
                    @foreach($recipes as $recipe)
                        @php
                            $baseCost = $recipe->items->sum(fn($item) => (float)($item->ingredient?->cost ?? 0) * (float)$item->quantity * (1 + (float)$item->waste_percent / 100));
                            $unitCost = $baseCost / max(.0001, (float)$recipe->yield_quantity);
                        @endphp
                        <article class="group overflow-hidden rounded-2xl border border-slate-200 bg-white transition hover:-translate-y-0.5 hover:border-orange-200 hover:shadow-lg">
                            <button wire:click="select({{$recipe->id}})" class="w-full p-5 text-left focus:outline-none focus:ring-4 focus:ring-inset focus:ring-orange-100">
                                <div class="flex items-start justify-between gap-3"><span class="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-orange-100 to-amber-50 text-lg font-black text-orange-700">{{mb_strtoupper(mb_substr($recipe->product?->name ?? '?',0,1))}}</span><span class="rounded-full px-2.5 py-1 text-[11px] font-black {{$recipe->is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}}">{{$recipe->is_active?'ATIVA':'INATIVA'}}</span></div>
                                <h2 class="mt-4 truncate text-lg font-black text-slate-900" title="{{$recipe->product?->name}}">{{$recipe->product?->name}}</h2><p class="mt-1 text-xs font-semibold text-slate-400">{{$recipe->product?->code ?: 'Sem código'}}</p>
                                <div class="mt-4 grid grid-cols-3 gap-2 text-center"><div class="rounded-xl bg-slate-50 p-2"><strong class="block text-sm text-slate-900">{{$recipe->items->count()}}</strong><span class="text-[10px] uppercase text-slate-400">Itens</span></div><div class="rounded-xl bg-slate-50 p-2"><strong class="block text-sm text-slate-900">{{(float)$recipe->yield_quantity}} {{$recipe->yield_unit}}</strong><span class="text-[10px] uppercase text-slate-400">Rende</span></div><div class="rounded-xl bg-orange-50 p-2"><strong class="block truncate text-sm text-orange-700">{{number_format($unitCost,0,',','.')}} Kz</strong><span class="text-[10px] uppercase text-orange-400">Custo/un.</span></div></div>
                            </button>
                            <div class="flex items-center justify-between border-t border-slate-100 px-5 py-3"><button wire:click="toggleActive({{$recipe->id}})" class="text-xs font-bold {{$recipe->is_active?'text-emerald-600':'text-slate-500'}}"><i class="fas {{$recipe->is_active?'fa-toggle-on':'fa-toggle-off'}} mr-1"></i>{{$recipe->is_active?'Ativa':'Inativa'}}</button><div class="flex gap-1"><button wire:click="select({{$recipe->id}})" class="grid h-9 w-9 place-items-center rounded-lg text-blue-600 hover:bg-blue-50" aria-label="Editar {{$recipe->product?->name}}"><i class="fas fa-pen"></i></button><button wire:click="deleteRecipe({{$recipe->id}})" wire:confirm="Eliminar esta ficha técnica e os seus ingredientes?" class="grid h-9 w-9 place-items-center rounded-lg text-red-500 hover:bg-red-50" aria-label="Eliminar {{$recipe->product?->name}}"><i class="fas fa-trash"></i></button></div></div>
                        </article>
                    @endforeach
                </div>
            @else
                <div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left"><thead><tr class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><th class="px-5 py-3">Produto</th><th class="px-4 py-3">Rendimento</th><th class="px-4 py-3">Ingredientes</th><th class="px-4 py-3">Custo estimado</th><th class="px-4 py-3">Estado</th><th class="px-5 py-3 text-right">Ações</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($recipes as $recipe)@php $baseCost=$recipe->items->sum(fn($item)=>(float)($item->ingredient?->cost??0)*(float)$item->quantity*(1+(float)$item->waste_percent/100)); @endphp<tr class="transition hover:bg-orange-50/40"><td class="px-5 py-4"><button wire:click="select({{$recipe->id}})" class="flex items-center gap-3 text-left"><span class="grid h-10 w-10 place-items-center rounded-xl bg-orange-50 font-black text-orange-700">{{mb_strtoupper(mb_substr($recipe->product?->name??'?',0,1))}}</span><span><b class="block text-slate-900">{{$recipe->product?->name}}</b><small class="text-slate-400">{{$recipe->product?->code ?: 'Sem código'}}</small></span></button></td><td class="px-4 py-4 font-bold text-slate-700">{{(float)$recipe->yield_quantity}} {{$recipe->yield_unit}}</td><td class="px-4 py-4 text-slate-600">{{$recipe->items->count()}}</td><td class="px-4 py-4 font-black text-orange-700">{{number_format($baseCost/max(.0001,(float)$recipe->yield_quantity),2,',','.')}} Kz/un.</td><td class="px-4 py-4"><button wire:click="toggleActive({{$recipe->id}})" class="rounded-full px-3 py-1 text-xs font-black {{$recipe->is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}}">{{$recipe->is_active?'Ativa':'Inativa'}}</button></td><td class="px-5 py-4"><div class="flex justify-end gap-1"><button wire:click="select({{$recipe->id}})" class="grid h-9 w-9 place-items-center rounded-lg text-blue-600 hover:bg-blue-50"><i class="fas fa-pen"></i></button><button wire:click="deleteRecipe({{$recipe->id}})" wire:confirm="Eliminar esta ficha técnica?" class="grid h-9 w-9 place-items-center rounded-lg text-red-500 hover:bg-red-50"><i class="fas fa-trash"></i></button></div></td></tr>@endforeach</tbody></table></div>
            @endif
        </section>
    </div>

    @if($showEditor)
        <div class="fixed inset-0 z-[120] flex items-end justify-center bg-slate-950/65 p-0 backdrop-blur-sm sm:items-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="recipe-editor-title">
            <section class="max-h-[94vh] w-full overflow-hidden rounded-t-3xl bg-white shadow-2xl sm:max-w-5xl sm:rounded-3xl">
                <header class="flex items-center justify-between border-b border-slate-200 px-5 py-4 sm:px-6"><div><p class="text-xs font-black uppercase tracking-wider text-orange-600">{{$recipeId?'Editar receita':'Nova receita'}}</p><h2 id="recipe-editor-title" class="mt-1 text-xl font-black text-slate-900">{{$selected?->product?->name ?? 'Ficha técnica'}}</h2></div><button wire:click="closeEditor" class="grid h-11 w-11 place-items-center rounded-xl bg-slate-100 text-xl text-slate-600 hover:bg-slate-200" aria-label="Fechar editor">×</button></header>
                <div class="max-h-[calc(94vh-78px)] overflow-y-auto">
                    <div class="grid lg:grid-cols-[360px_minmax(0,1fr)]">
                        <aside class="border-b border-slate-200 bg-slate-50 p-5 sm:p-6 lg:border-b-0 lg:border-r">
                            <h3 class="font-black text-slate-900">Produto e rendimento</h3><p class="mt-1 text-xs text-slate-500">Defina quantas doses ou unidades esta receita produz.</p>
                            <label class="mt-5 block text-sm font-bold text-slate-700">Produto vendido<select wire:model="productId" class="mt-2 w-full rounded-xl border-slate-300 bg-white focus:border-orange-400 focus:ring-orange-200"><option value="">Selecionar produto</option>@foreach($products as $product)<option value="{{$product->id}}">{{$product->name}}</option>@endforeach</select></label>@error('productId')<p class="mt-1 text-xs font-bold text-red-600">{{$message}}</p>@enderror
                            <div class="mt-4 grid grid-cols-[1fr_110px] gap-3"><label class="text-sm font-bold text-slate-700">Rendimento<input type="number" step=".001" min=".001" wire:model="yieldQuantity" class="mt-2 w-full rounded-xl border-slate-300 bg-white focus:border-orange-400 focus:ring-orange-200"></label><label class="text-sm font-bold text-slate-700">Unidade<select wire:model="yieldUnit" class="mt-2 w-full rounded-xl border-slate-300 bg-white"><option>UN</option><option>DOSE</option><option>KG</option><option>L</option></select></label></div>
                            <button wire:click="saveRecipe" wire:loading.attr="disabled" class="mt-5 w-full rounded-xl bg-slate-900 px-4 py-3 font-black text-white transition hover:bg-slate-800 disabled:opacity-50"><span wire:loading.remove wire:target="saveRecipe"><i class="fas fa-floppy-disk mr-2"></i>Guardar dados</span><span wire:loading wire:target="saveRecipe">A guardar...</span></button>
                            @if(!$recipeId)<div class="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-700"><i class="fas fa-circle-info mr-1"></i>Guarde primeiro os dados para ativar a área de ingredientes.</div>@endif
                        </aside>

                        <main class="p-5 sm:p-6">
                            <div class="flex items-start justify-between gap-3"><div><h3 class="font-black text-slate-900">Ingredientes</h3><p class="mt-1 text-xs text-slate-500">Quantidade utilizada para o rendimento indicado.</p></div>@if($selected)<span class="rounded-full bg-orange-50 px-3 py-1 text-xs font-black text-orange-700">{{$selected->items->count()}} item(ns)</span>@endif</div>
                            @if($recipeId)
                                <div class="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-[minmax(180px,2fr)_100px_90px_100px_auto]"><label class="text-xs font-bold text-slate-600">Ingrediente<select wire:model="ingredientId" class="mt-1 w-full rounded-xl border-slate-300 bg-white"><option value="">Selecionar</option>@foreach($products as $product)<option value="{{$product->id}}">{{$product->name}}</option>@endforeach</select></label><label class="text-xs font-bold text-slate-600">Quantidade<input type="number" step=".001" min=".001" wire:model="ingredientQuantity" class="mt-1 w-full rounded-xl border-slate-300 bg-white"></label><label class="text-xs font-bold text-slate-600">Unidade<select wire:model="ingredientUnit" class="mt-1 w-full rounded-xl border-slate-300 bg-white"><option>UN</option><option>G</option><option>KG</option><option>ML</option><option>L</option></select></label><label class="text-xs font-bold text-slate-600">Perda %<input type="number" min="0" max="100" step=".01" wire:model="wastePercent" class="mt-1 w-full rounded-xl border-slate-300 bg-white"></label><button wire:click="addIngredient" class="self-end rounded-xl bg-emerald-600 px-4 py-3 font-black text-white hover:bg-emerald-700"><i class="fas fa-plus mr-1"></i>Adicionar</button></div>@error('ingredientId')<p class="mt-2 text-xs font-bold text-red-600">{{$message}}</p>@enderror</div>
                                <div class="mt-4 overflow-hidden rounded-2xl border border-slate-200"><div class="hidden grid-cols-[minmax(0,1fr)_110px_110px_80px] bg-slate-50 px-4 py-3 text-xs font-bold uppercase text-slate-400 sm:grid"><span>Ingrediente</span><span>Quantidade</span><span>Custo estimado</span><span class="text-right">Ação</span></div><div class="divide-y divide-slate-100">@forelse($selected?->items ?? [] as $item)@php $cost=(float)($item->ingredient?->cost??0)*(float)$item->quantity*(1+(float)$item->waste_percent/100); @endphp<div class="grid gap-2 px-4 py-4 sm:grid-cols-[minmax(0,1fr)_110px_110px_80px] sm:items-center"><div><b class="text-slate-900">{{$item->ingredient?->name}}</b><p class="text-xs text-slate-400">{{$item->ingredient?->code ?: 'Sem código'}} · perda {{$item->waste_percent}}%</p></div><span class="text-sm font-bold text-slate-700">{{(float)$item->quantity}} {{$item->unit}}</span><span class="text-sm font-black text-orange-700">{{number_format($cost,2,',','.')}} Kz</span><button wire:click="removeIngredient({{$item->id}})" wire:confirm="Remover este ingrediente?" class="justify-self-start rounded-lg px-3 py-2 text-sm font-bold text-red-600 hover:bg-red-50 sm:justify-self-end" aria-label="Remover {{$item->ingredient?->name}}"><i class="fas fa-trash"></i></button></div>@empty<div class="px-6 py-12 text-center"><span class="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-slate-100 text-xl text-slate-400"><i class="fas fa-carrot"></i></span><p class="mt-3 font-bold text-slate-700">Sem ingredientes</p><p class="mt-1 text-xs text-slate-400">Adicione o primeiro ingrediente acima.</p></div>@endforelse</div></div>
                            @else
                                <div class="mt-5 grid min-h-64 place-items-center rounded-2xl border-2 border-dashed border-slate-200 text-center"><div><i class="fas fa-arrow-left text-2xl text-slate-300"></i><p class="mt-3 font-bold text-slate-600">Guarde os dados da receita primeiro</p></div></div>
                            @endif
                        </main>
                    </div>
                </div>
            </section>
        </div>
    @endif
</div>
