<div class="space-y-6">
    <div><p class="text-sm font-bold uppercase tracking-wider text-orange-500">Restaurante</p><h1 class="text-3xl font-black text-white">Pedidos de estabelecimentos</h1><p class="mt-1 text-slate-400">Controle quantas unidades cada empresa pode operar sem contornar o plano contratado.</p></div>
    <div class="grid gap-4 sm:grid-cols-3">
        @foreach([['pending','Pendentes','amber'],['approved','Aprovados','emerald'],['rejected','Recusados','red']] as [$key,$label,$color])
            <button wire:click="$set('status','{{$key}}')" class="rounded-2xl border p-5 text-left transition {{$status===$key?'border-'.$color.'-400 bg-'.$color.'-500/10':'border-slate-700 bg-slate-800/70 hover:border-slate-500'}}"><span class="text-sm text-slate-400">{{$label}}</span><strong class="mt-1 block text-3xl text-white">{{$counts[$key] ?? 0}}</strong></button>
        @endforeach
    </div>
    <div class="rounded-2xl border border-slate-700 bg-slate-800/70 p-4"><input wire:model.live.debounce.300ms="search" class="w-full rounded-xl border-slate-600 bg-slate-900 text-white" placeholder="Pesquisar empresa..."></div>
    <div class="overflow-hidden rounded-2xl border border-slate-700 bg-slate-800/70">
        <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-900/70 text-left text-xs uppercase text-slate-400"><tr><th class="p-4">Empresa</th><th class="p-4">Quota</th><th class="p-4">Pedido</th><th class="p-4">Motivo</th><th class="p-4">Estado</th><th class="p-4"></th></tr></thead><tbody class="divide-y divide-slate-700">
        @forelse($requests as $request)<tr class="text-slate-200"><td class="p-4"><b class="block text-white">{{$request->tenant?->company_name ?: $request->tenant?->name}}</b><span class="text-xs text-slate-400">{{$request->requester?->name}} · {{$request->created_at->format('d/m/Y H:i')}}</span></td><td class="p-4">{{$request->current_limit}}</td><td class="p-4 font-black text-orange-400">{{$request->requested_limit}}</td><td class="max-w-sm p-4 text-slate-400">{{$request->reason ?: 'Sem observação'}}</td><td class="p-4"><span class="rounded-full px-3 py-1 text-xs font-bold {{$request->status==='approved'?'bg-emerald-500/15 text-emerald-300':($request->status==='rejected'?'bg-red-500/15 text-red-300':'bg-amber-500/15 text-amber-300')}}">{{$request->status === 'approved' ? 'Aprovado' : ($request->status === 'rejected' ? 'Recusado' : 'Pendente')}}</span></td><td class="p-4">@if($request->status==='pending')<button wire:click="openReview({{$request->id}})" class="rounded-xl bg-orange-500 px-4 py-2 font-black text-white hover:bg-orange-400">Analisar</button>@else<span class="text-xs text-slate-500">{{$request->reviewed_at?->format('d/m/Y H:i')}}</span>@endif</td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-slate-400">Nenhum pedido neste estado.</td></tr>@endforelse
        </tbody></table></div><div class="border-t border-slate-700 p-4">{{$requests->links()}}</div>
    </div>
    @if($reviewingId)<div class="fixed inset-0 z-[100] grid place-items-center bg-slate-950/80 p-4"><div class="w-full max-w-lg rounded-3xl border border-slate-700 bg-slate-900 p-6 shadow-2xl"><div class="flex justify-between"><div><p class="text-xs font-black uppercase text-orange-400">Autorização</p><h2 class="text-2xl font-black text-white">Analisar pedido</h2></div><button wire:click="$set('reviewingId',null)" class="h-10 w-10 rounded-xl bg-slate-800 text-white">×</button></div><label class="mt-5 block font-bold text-slate-200">Novo limite aprovado<input type="number" min="2" max="100" wire:model="approvedLimit" class="mt-2 w-full rounded-xl border-slate-600 bg-slate-800 text-white"></label><label class="mt-4 block font-bold text-slate-200">Nota do administrador<textarea wire:model="adminNotes" rows="4" class="mt-2 w-full rounded-xl border-slate-600 bg-slate-800 text-white" placeholder="Condição comercial ou motivo da decisão"></textarea></label><div class="mt-5 grid grid-cols-2 gap-3"><button wire:click="reject" class="rounded-xl bg-red-600 p-3 font-black text-white">Recusar</button><button wire:click="approve" class="rounded-xl bg-emerald-600 p-3 font-black text-white">Aprovar quota</button></div></div></div>@endif
</div>
