<?php

/**
 * Traduções do menu lateral e do painel de facturação.
 *
 * Notas de tradução que não são óbvias e que se perdem se não ficarem escritas:
 *
 *   · Recibos ≠ Recebimentos. O primeiro é o documento (Receipt / Reçu), o
 *     segundo é dinheiro que entrou (Amounts Received / Encaissements). Em
 *     português distinguem-se por uma letra e é o erro fácil de fazer.
 *
 *   · Turnos vale duas coisas. No RH é o horário de trabalho (Shifts /
 *     Équipes); no POS é a sessão de caixa (Cash Shifts / Sessions de caisse),
 *     e essa já ficou fixada no lote 2.
 *
 *   · Billing (Super Admin) não é Facturação (módulo). O primeiro são as
 *     assinaturas que cobramos aos inquilinos, o segundo são as facturas que
 *     eles emitem aos clientes deles. Em francês os dois dariam "Facturation",
 *     por isso o de cima ficou "Abonnements".
 *
 *   · Tenants em francês não é "Locataires" — isso são inquilinos de casas.
 *     Ficou "Entreprises", que é o que são.
 *
 *   · Hóspedes ficou "Hôtes" e não "Clients": no hotel já há Clientes, e ter
 *     as duas coisas com o mesmo nome no mesmo menu não ajudava ninguém.
 *
 * Uso:  php scripts/lote3_menu_traducoes.php
 */

$raiz = dirname(__DIR__);

$en = [
    ':n fatura|:n faturas' => ':n invoice|:n invoices',
    ':pct% vs mês anterior' => ':pct% vs last month',
    'Adiantamentos' => 'Advances',
    'Agendamentos' => 'Appointments',
    'Aging de Clientes' => 'Customer Aging',
    'AGT Angola' => 'AGT Angola',
    'Aguardando pagamento' => 'Awaiting payment',
    'Ajustes de Stock' => 'Stock Adjustments',
    'Analítica' => 'Analytics',
    'Análise de Margem' => 'Margin Analysis',
    'Armazéns' => 'Warehouses',
    'Atividades Recentes' => 'Recent Activity',
    'Atualizações do Sistema' => 'System Updates',
    'Auditoria' => 'Audit',
    'Bancos' => 'Banks',
    'Bem-vindo ao sistema' => 'Welcome to the system',
    'Billing' => 'Billing',
    'Caixas' => 'Cash Registers',
    'Calendário' => 'Calendar',
    'Categorias' => 'Categories',
    'Centros Custo' => 'Cost Centres',
    'Check-out' => 'Check-out',
    'Cliente: :nome • :quando' => 'Customer: :nome • :quando',
    'Clientes' => 'Customers',
    'Cobranças extras' => 'Extra charges',
    'Comandas' => 'Tickets',
    'Comparativo' => 'Comparison',
    'Comparação Ano a Ano' => 'Year-on-Year Comparison',
    'Configurações' => 'Settings',
    'Configurações do Sistema' => 'System Settings',
    'Configurações RH' => 'HR Settings',
    'Contabilidade' => 'Accounting',
    'Contagem de Stock' => 'Stock Count',
    'Contas a Pagar' => 'Accounts Payable',
    'Contas a Receber' => 'Accounts Receivable',
    'Contas Bancárias' => 'Bank Accounts',
    'Cozinha / KDS' => 'Kitchen / KDS',
    'Crescimento' => 'Growth',
    'CRM' => 'CRM',
    'Dashboard' => 'Dashboard',
    'Dashboard de Faturação' => 'Invoicing Dashboard',
    'Departamentos' => 'Departments',
    'Descontos Salariais' => 'Payroll Deductions',
    'Desempenho de Produtos' => 'Product Performance',
    'Devoluções' => 'Returns',
    'Diários' => 'Journals',
    'Documentos' => 'Documents',
    'Documentos Este Mês' => 'Documents This Month',
    'Encomendas' => 'Orders',
    'Equipamentos' => 'Equipment',
    'Estado das Faturas' => 'Invoice Status',
    'Esta Semana' => 'This Week',
    'Este Ano' => 'This Year',
    'Este Mês' => 'This Month',
    'estimado' => 'estimated',
    'Eventos' => 'Events',
    'Evolução de Vendas - :periodo' => 'Sales Trend - :periodo',
    'Executar Scripts' => 'Run Scripts',
    'Exportar PDF' => 'Export PDF',
    'Extracto de Conta Corrente' => 'Account Statement',
    'Facturação' => 'Invoicing',
    'Fatura <strong>:numero</strong> criada' => 'Invoice <strong>:numero</strong> created',
    'Faturas' => 'Invoices',
    'Faturas Compra' => 'Purchase Invoices',
    'Faturas Pendentes' => 'Pending Invoices',
    'Faturas Venda' => 'Sales Invoices',
    'Faturação :ano' => 'Revenue :ano',
    'Faturação do Mês' => 'Monthly Revenue',
    'Fichas Técnicas' => 'Technical Sheets',
    'Folha de Pagamento' => 'Payroll',
    'Fornecedores' => 'Suppliers',
    'FOX Friendly activo!' => 'FOX Friendly active!',
    'Funcionários' => 'Employees',
    'Funil de Vendas' => 'Sales Pipeline',
    'Férias' => 'Leave',
    'Gerado em: :data' => 'Generated on: :data',
    'Gerador SAFT-AO' => 'SAFT-AO Generator',
    'Gestão de Hotel' => 'Hotel Management',
    'Gestão de Oficina' => 'Workshop Management',
    'Gestão de Utilizadores' => 'User Management',
    'Gestão Stock' => 'Stock Management',
    'Guias Transporte' => 'Delivery Notes',
    'Horas Extras' => 'Overtime',
    'Housekeeping' => 'Housekeeping',
    'Hóspedes' => 'Guests',
    'Imobilizado' => 'Fixed Assets',
    'Importações' => 'Imports',
    'Impostos (IVA)' => 'Taxes (VAT)',
    'Iniciar sessão' => 'Log in',
    'Inventário' => 'Inventory',
    'Início' => 'Home',
    'Lançamentos' => 'Entries',
    'Leads' => 'Leads',
    'Licenças e Faltas' => 'Leave & Absences',
    'Locais' => 'Locations',
    'Lotes e Validades' => 'Batches & Expiry',
    'Lucros e Perdas (DRE)' => 'Profit & Loss',
    'Manutenção' => 'Maintenance',
    'Mapa de Compras' => 'Purchases Report',
    'Mapa de Documentos' => 'Documents Report',
    'Mapa de IVA' => 'VAT Report',
    'Mapa de Serviços' => 'Services Report',
    'Mapa de Vendas' => 'Sales Report',
    'Marcas' => 'Brands',
    'Mecânicos' => 'Mechanics',
    'Melhor Fornecedor' => 'Top Supplier',
    'Menu Principal' => 'Main Menu',
    'Modelos' => 'Models',
    'Moedas' => 'Currencies',
    'Movimentos' => 'Movements',
    'Métodos de Pagamento' => 'Payment Methods',
    'Módulos' => 'Modules',
    'Nenhuma fatura pendente' => 'No pending invoices',
    'Notas Crédito' => 'Credit Notes',
    'Notas Débito' => 'Debit Notes',
    'Notificações' => 'Notifications',
    'Novo' => 'New',
    'Oportunidades' => 'Opportunities',
    'Optimização & OPcache' => 'Optimisation & OPcache',
    'Ordens de Serviço' => 'Work Orders',
    'Orçamentos' => 'Quotes',
    'Pacotes' => 'Packages',
    'Pagamentos' => 'Payments',
    'Pagamentos recebidos' => 'Payments received',
    'Painel de Relatórios' => 'Reports Dashboard',
    'Parc. Pagas' => 'Part. Paid',
    'Períodos' => 'Periods',
    'Peças' => 'Parts',
    'Plano de Contas' => 'Chart of Accounts',
    'Planos' => 'Plans',
    'Por faturação' => 'By revenue',
    'Por inatividade, a sua sessão terminou. <strong>O carrinho foi guardado</strong> e será restaurado assim que iniciar sessão novamente.'
        => 'Your session ended due to inactivity. <strong>Your cart has been saved</strong> and will be restored as soon as you log in again.',
    'POS / Faturar' => 'POS / Invoice',
    'POS Offline (PWA)' => 'Offline POS (PWA)',
    'Presenças' => 'Attendance',
    'Profissionais' => 'Professionals',
    'Proformas Compra' => 'Purchase Proformas',
    'Proformas Venda' => 'Sales Proformas',
    'Projetos' => 'Projects',
    'Quartos' => 'Rooms',
    'Recebimentos' => 'Amounts Received',
    'Recebimentos por Meio' => 'Receipts by Method',
    'Reconciliação' => 'Reconciliation',
    'Recursos Humanos' => 'Human Resources',
    'Relatório PDF gerado com sucesso!' => 'PDF report generated successfully!',
    'Relatórios' => 'Reports',
    'Relatórios POS' => 'POS Reports',
    'Relatório Validade' => 'Expiry Report',
    'Requer atenção' => 'Needs attention',
    'Requisições' => 'Requisitions',
    'Reservas' => 'Bookings',
    'Restaurante' => 'Restaurant',
    'Roles & Permissões' => 'Roles & Permissions',
    'SAFT Configurações' => 'SAFT Settings',
    'Sala e Mesas' => 'Room & Tables',
    'Salão de Beleza' => 'Beauty Salon',
    'Sem alteração' => 'No change',
    'Sem atividades recentes' => 'No recent activity',
    'Sem cliente' => 'No customer',
    'Sem dados de clientes' => 'No customer data',
    'Serviços' => 'Services',
    'Sessão expirada' => 'Session expired',
    'Sistema' => 'System',
    'Stock e Desperdícios' => 'Stock & Waste',
    'Super Admin' => 'Super Admin',
    'Suporte' => 'Support',
    'Séries de Documentos' => 'Document Series',
    'Tabela de Preços e Lucro' => 'Price & Margin List',
    'Tarefas' => 'Tasks',
    'Tarifas' => 'Rates',
    'Tenants' => 'Tenants',
    'Tesouraria' => 'Treasury',
    'Timesheet' => 'Timesheet',
    'Tipos de Documentos' => 'Document Types',
    'Tipos de Eventos' => 'Event Types',
    'Tipos de Quarto' => 'Room Types',
    'Top 5 Clientes' => 'Top 5 Customers',
    'Top Clientes' => 'Top Customers',
    'Top Fornecedores' => 'Top Suppliers',
    'Top Produtos' => 'Top Products',
    'Transações' => 'Transactions',
    'Transfer. Armazéns' => 'Warehouse Transfers',
    'Transfer. Inter-Empresa' => 'Inter-Company Transfers',
    'Transferências' => 'Transfers',
    'Turno Noturno' => 'Night Shift',
    'Turnos' => 'Shifts',
    'Turnos de Caixa' => 'Cash Shifts',
    'Técnicos' => 'Technicians',
    'Utilizadores' => 'Users',
    'Validade de Produtos' => 'Product Expiry',
    'Valor (AOA)' => 'Value (AOA)',
    'Valores antecipados' => 'Prepaid amounts',
    'Valores Pendentes' => 'Outstanding',
    'Valores Vencidos' => 'Overdue',
    'Venc.: :data' => 'Due: :data',
    'Vencida' => 'Overdue',
    'Vencidas' => 'Overdue',
    'Vendas (AOA)' => 'Sales (AOA)',
    'Vendas emitidas' => 'Sales issued',
    'Vendas por Vendedor' => 'Sales by Salesperson',
    'Ver todas' => 'View all',
    'Veículos' => 'Vehicles',
    'Visão geral do módulo de faturação - :periodo' => 'Invoicing module overview - :periodo',
    'vs mês anterior' => 'vs last month',
    'Walk-in' => 'Walk-in',
];

$fr = [
    ':n fatura|:n faturas' => ':n facture|:n factures',
    ':pct% vs mês anterior' => ':pct % vs mois précédent',
    'Adiantamentos' => 'Acomptes',
    'Agendamentos' => 'Rendez-vous',
    'Aging de Clientes' => 'Balance âgée clients',
    'AGT Angola' => 'AGT Angola',
    'Aguardando pagamento' => 'En attente de paiement',
    'Ajustes de Stock' => 'Ajustements de stock',
    'Analítica' => 'Analytique',
    'Análise de Margem' => 'Analyse de marge',
    'Armazéns' => 'Entrepôts',
    'Atividades Recentes' => 'Activité récente',
    'Atualizações do Sistema' => 'Mises à jour du système',
    'Auditoria' => 'Audit',
    'Bancos' => 'Banques',
    'Bem-vindo ao sistema' => 'Bienvenue dans le système',
    'Billing' => 'Abonnements',
    'Caixas' => 'Caisses',
    'Calendário' => 'Calendrier',
    'Categorias' => 'Catégories',
    'Centros Custo' => 'Centres de coûts',
    'Check-out' => 'Check-out',
    'Cliente: :nome • :quando' => 'Client : :nome • :quando',
    'Clientes' => 'Clients',
    'Cobranças extras' => 'Frais supplémentaires',
    'Comandas' => 'Tickets',
    'Comparativo' => 'Comparatif',
    'Comparação Ano a Ano' => 'Comparaison annuelle',
    'Configurações' => 'Paramètres',
    'Configurações do Sistema' => 'Paramètres du système',
    'Configurações RH' => 'Paramètres RH',
    'Contabilidade' => 'Comptabilité',
    'Contagem de Stock' => 'Inventaire physique',
    'Contas a Pagar' => 'Comptes fournisseurs',
    'Contas a Receber' => 'Comptes clients',
    'Contas Bancárias' => 'Comptes bancaires',
    'Cozinha / KDS' => 'Cuisine / KDS',
    'Crescimento' => 'Croissance',
    'CRM' => 'CRM',
    'Dashboard' => 'Tableau de bord',
    'Dashboard de Faturação' => 'Tableau de bord de facturation',
    'Departamentos' => 'Départements',
    'Descontos Salariais' => 'Retenues salariales',
    'Desempenho de Produtos' => 'Performance des produits',
    'Devoluções' => 'Retours',
    'Diários' => 'Journaux',
    'Documentos' => 'Documents',
    'Documentos Este Mês' => 'Documents ce mois-ci',
    'Encomendas' => 'Commandes',
    'Equipamentos' => 'Équipements',
    'Estado das Faturas' => 'Statut des factures',
    'Esta Semana' => 'Cette semaine',
    'Este Ano' => 'Cette année',
    'Este Mês' => 'Ce mois-ci',
    'estimado' => 'estimé',
    'Eventos' => 'Événements',
    'Evolução de Vendas - :periodo' => 'Évolution des ventes - :periodo',
    'Executar Scripts' => 'Exécuter des scripts',
    'Exportar PDF' => 'Exporter en PDF',
    'Extracto de Conta Corrente' => 'Relevé de compte',
    'Facturação' => 'Facturation',
    'Fatura <strong>:numero</strong> criada' => 'Facture <strong>:numero</strong> créée',
    'Faturas' => 'Factures',
    'Faturas Compra' => 'Factures d\'achat',
    'Faturas Pendentes' => 'Factures en attente',
    'Faturas Venda' => 'Factures de vente',
    'Faturação :ano' => 'Chiffre d\'affaires :ano',
    'Faturação do Mês' => 'Chiffre d\'affaires du mois',
    'Fichas Técnicas' => 'Fiches techniques',
    'Folha de Pagamento' => 'Paie',
    'Fornecedores' => 'Fournisseurs',
    'FOX Friendly activo!' => 'FOX Friendly actif !',
    'Funcionários' => 'Employés',
    'Funil de Vendas' => 'Pipeline de ventes',
    'Férias' => 'Congés',
    'Gerado em: :data' => 'Généré le : :data',
    'Gerador SAFT-AO' => 'Générateur SAFT-AO',
    'Gestão de Hotel' => 'Gestion hôtelière',
    'Gestão de Oficina' => 'Gestion d\'atelier',
    'Gestão de Utilizadores' => 'Gestion des utilisateurs',
    'Gestão Stock' => 'Gestion de stock',
    'Guias Transporte' => 'Bons de livraison',
    'Horas Extras' => 'Heures supplémentaires',
    'Housekeeping' => 'Housekeeping',
    'Hóspedes' => 'Hôtes',
    'Imobilizado' => 'Immobilisations',
    'Importações' => 'Importations',
    'Impostos (IVA)' => 'Taxes (TVA)',
    'Iniciar sessão' => 'Se connecter',
    'Inventário' => 'Inventaire',
    'Início' => 'Accueil',
    'Lançamentos' => 'Écritures',
    'Leads' => 'Prospects',
    'Licenças e Faltas' => 'Congés et absences',
    'Locais' => 'Sites',
    'Lotes e Validades' => 'Lots et péremption',
    'Lucros e Perdas (DRE)' => 'Compte de résultat',
    'Manutenção' => 'Maintenance',
    'Mapa de Compras' => 'État des achats',
    'Mapa de Documentos' => 'État des documents',
    'Mapa de IVA' => 'État de TVA',
    'Mapa de Serviços' => 'État des services',
    'Mapa de Vendas' => 'État des ventes',
    'Marcas' => 'Marques',
    'Mecânicos' => 'Mécaniciens',
    'Melhor Fornecedor' => 'Meilleur fournisseur',
    'Menu Principal' => 'Menu principal',
    'Modelos' => 'Modèles',
    'Moedas' => 'Devises',
    'Movimentos' => 'Mouvements',
    'Métodos de Pagamento' => 'Modes de paiement',
    'Módulos' => 'Modules',
    'Nenhuma fatura pendente' => 'Aucune facture en attente',
    'Notas Crédito' => 'Avoirs',
    'Notas Débito' => 'Notes de débit',
    'Notificações' => 'Notifications',
    'Novo' => 'Nouveau',
    'Oportunidades' => 'Opportunités',
    'Optimização & OPcache' => 'Optimisation et OPcache',
    'Ordens de Serviço' => 'Ordres de travail',
    'Orçamentos' => 'Devis',
    'Pacotes' => 'Forfaits',
    'Pagamentos' => 'Paiements',
    'Pagamentos recebidos' => 'Paiements reçus',
    'Painel de Relatórios' => 'Tableau de bord des rapports',
    'Parc. Pagas' => 'Part. payées',
    'Períodos' => 'Périodes',
    'Peças' => 'Pièces',
    'Plano de Contas' => 'Plan comptable',
    'Planos' => 'Plans',
    'Por faturação' => 'Par chiffre d\'affaires',
    'Por inatividade, a sua sessão terminou. <strong>O carrinho foi guardado</strong> e será restaurado assim que iniciar sessão novamente.'
        => 'Votre session a pris fin pour cause d\'inactivité. <strong>Votre panier a été enregistré</strong> et sera restauré dès votre reconnexion.',
    'POS / Faturar' => 'POS / Facturer',
    'POS Offline (PWA)' => 'POS hors ligne (PWA)',
    'Presenças' => 'Présences',
    'Profissionais' => 'Professionnels',
    'Proformas Compra' => 'Proformas d\'achat',
    'Proformas Venda' => 'Proformas de vente',
    'Projetos' => 'Projets',
    'Quartos' => 'Chambres',
    'Recebimentos' => 'Encaissements',
    'Recebimentos por Meio' => 'Encaissements par mode',
    'Reconciliação' => 'Rapprochement',
    'Recursos Humanos' => 'Ressources humaines',
    'Relatório PDF gerado com sucesso!' => 'Rapport PDF généré avec succès !',
    'Relatórios' => 'Rapports',
    'Relatórios POS' => 'Rapports POS',
    'Relatório Validade' => 'Rapport de péremption',
    'Requer atenção' => 'Nécessite une attention',
    'Requisições' => 'Demandes',
    'Reservas' => 'Réservations',
    'Restaurante' => 'Restaurant',
    'Roles & Permissões' => 'Rôles et permissions',
    'SAFT Configurações' => 'Paramètres SAFT',
    'Sala e Mesas' => 'Salle et tables',
    'Salão de Beleza' => 'Salon de beauté',
    'Sem alteração' => 'Aucun changement',
    'Sem atividades recentes' => 'Aucune activité récente',
    'Sem cliente' => 'Sans client',
    'Sem dados de clientes' => 'Aucune donnée client',
    'Serviços' => 'Services',
    'Sessão expirada' => 'Session expirée',
    'Sistema' => 'Système',
    'Stock e Desperdícios' => 'Stock et pertes',
    'Super Admin' => 'Super Admin',
    'Suporte' => 'Support',
    'Séries de Documentos' => 'Séries de documents',
    'Tabela de Preços e Lucro' => 'Tarifs et marges',
    'Tarefas' => 'Tâches',
    'Tarifas' => 'Tarifs',
    'Tenants' => 'Entreprises',
    'Tesouraria' => 'Trésorerie',
    'Timesheet' => 'Feuille de temps',
    'Tipos de Documentos' => 'Types de documents',
    'Tipos de Eventos' => 'Types d\'événements',
    'Tipos de Quarto' => 'Types de chambre',
    'Top 5 Clientes' => 'Top 5 clients',
    'Top Clientes' => 'Meilleurs clients',
    'Top Fornecedores' => 'Meilleurs fournisseurs',
    'Top Produtos' => 'Meilleurs produits',
    'Transações' => 'Transactions',
    'Transfer. Armazéns' => 'Transferts entrepôts',
    'Transfer. Inter-Empresa' => 'Transferts inter-sociétés',
    'Transferências' => 'Transferts',
    'Turno Noturno' => 'Service de nuit',
    'Turnos' => 'Équipes',
    'Turnos de Caixa' => 'Sessions de caisse',
    'Técnicos' => 'Techniciens',
    'Utilizadores' => 'Utilisateurs',
    'Validade de Produtos' => 'Péremption des produits',
    'Valor (AOA)' => 'Valeur (AOA)',
    'Valores antecipados' => 'Montants anticipés',
    'Valores Pendentes' => 'Montants en attente',
    'Valores Vencidos' => 'Montants échus',
    'Venc.: :data' => 'Éch. : :data',
    'Vencida' => 'Échue',
    'Vencidas' => 'Échues',
    'Vendas (AOA)' => 'Ventes (AOA)',
    'Vendas emitidas' => 'Ventes émises',
    'Vendas por Vendedor' => 'Ventes par vendeur',
    'Ver todas' => 'Tout voir',
    'Veículos' => 'Véhicules',
    'Visão geral do módulo de faturação - :periodo' => 'Aperçu du module de facturation - :periodo',
    'vs mês anterior' => 'vs mois précédent',
    'Walk-in' => 'Sans rendez-vous',
];

foreach (['en' => $en, 'fr' => $fr] as $lingua => $novas) {
    $caminho = "{$raiz}/lang/{$lingua}.json";
    $dicionario = json_decode(file_get_contents($caminho), true) ?: [];

    $acrescentadas = 0;
    $conflitos = [];

    foreach ($novas as $pt => $traduzida) {
        // Uma chave já traduzida noutro lote não se sobrepõe às cegas: se as
        // duas traduções diferirem é sinal de que uma delas está errada, e
        // isso quer-se ver, não resolver em silêncio.
        if (isset($dicionario[$pt])) {
            if ($dicionario[$pt] !== $traduzida) {
                $conflitos[$pt] = [$dicionario[$pt], $traduzida];
            }
            continue;
        }

        $dicionario[$pt] = $traduzida;
        $acrescentadas++;
    }

    ksort($dicionario, SORT_NATURAL | SORT_FLAG_CASE);

    file_put_contents(
        $caminho,
        json_encode($dicionario, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . "\n"
    );

    printf("lang/%s.json: +%d (total %d)\n", $lingua, $acrescentadas, count($dicionario));

    foreach ($conflitos as $pt => [$antiga, $nova]) {
        printf("    conflito em \"%s\": tinha \"%s\", propus \"%s\" — ficou a antiga\n", $pt, $antiga, $nova);
    }
}
