<?php

/**
 * Traduções do lote 5, parte A — compras, AGT, séries e definições.
 *
 * Notas de tradução que não são óbvias:
 *
 *   · O vocabulário da AGT não se traduz. Os códigos de documento (FT, FR,
 *     NC, ND, PR, RC, FC, AD, GT, GR), os nomes dos campos do payload
 *     (jwsSignature, eacCode, resultCode), os endpoints (RegistarFactura,
 *     ConsultarFactura) e os elementos do XML SAFT são identificadores
 *     definidos pelo Estado angolano: traduzi-los tornava-os inválidos.
 *
 *   · "Homologação" é o ambiente de testes da AGT. Em inglês diz-se Sandbox;
 *     em francês "homologation" existe e é o termo usado no mesmo contexto.
 *
 *   · "Factura" e "Fatura" convivem no código (grafia pré e pós-acordo).
 *     Traduzem-se as duas para a mesma coisa — a diferença é ortográfica
 *     portuguesa e não existe nas outras línguas.
 *
 *   · Markup e Margem não são a mesma conta: markup mede sobre o custo,
 *     margem sobre o preço. Em inglês são mesmo Markup e Margin; em francês
 *     "taux de marque" (sobre o preço) e "taux de marge" (sobre o custo)
 *     invertem-se entre si conforme a fonte, por isso ficam Markup e Marge,
 *     que é o que se usa nos ERP franceses.
 *
 * Uso:  php scripts/lote5a_compras_traducoes.php
 */

$raiz = dirname(__DIR__);

$en = [
    '% do Total' => '% of Total',
    '(+) Receita Bruta de Vendas' => '(+) Gross Sales Revenue',
    '(=) Receita Líquida' => '(=) Net Revenue',
    '(DS.120 §4.1)' => '(DS.120 §4.1)',
    '(DS.120 §4.5)' => '(DS.120 §4.5)',
    '(DS.120 §4.6)' => '(DS.120 §4.6)',
    '(vai no payload da AGT)' => '(goes in the AGT payload)',
    '(−) Custo dos Produtos Vendidos (CMV)' => '(−) Cost of Goods Sold (COGS)',
    '(−) Descontos concedidos' => '(−) Discounts granted',
    '(−) Devoluções (Notas de Crédito)' => '(−) Returns (Credit Notes)',
    '+120 dias' => '+120 days',
    '0 decimais - 20.000' => '0 decimals - 20,000',
    '000001 = Numeração sequencial' => '000001 = Sequential numbering',
    '1 decimal - 20.000,0' => '1 decimal - 20,000.0',
    '1-30 dias' => '1-30 days',
    '2 decimais - 20.000,00' => '2 decimals - 20,000.00',
    '3 decimais - 20.000,000' => '3 decimals - 20,000.000',
    '4 decimais - 20.000,0000' => '4 decimals - 20,000.0000',
    '7 dias' => '7 days',
    '8 produtos' => '8 products',
    '12 produtos' => '12 products',
    '15 dias' => '15 days',
    '16 produtos' => '16 products',
    '20 produtos' => '20 products',
    '24 produtos' => '24 products',
    '25 por página' => '25 per page',
    '31-60 dias' => '31-60 days',
    '50 por página' => '50 per page',
    '60 dias' => '60 days',
    '61-90 dias' => '61-90 days',
    '91-120 dias' => '91-120 days',
    '100 por página' => '100 per page',
    '<strong>Credenciais do produtor não configuradas.</strong> O administrador do sistema precisa configurar as credenciais Basic Auth (username/password) em <strong>Operação AGT → Configurações</strong> para que a comunicação com a API AGT funcione.'
        => '<strong>Producer credentials not configured.</strong> The system administrator needs to set the Basic Auth credentials (username/password) under <strong>AGT Operations → Settings</strong> for communication with the AGT API to work.',
    '<strong>O que configurar aqui:</strong> O NIF do contribuinte, o código do estabelecimento e a <strong>chave privada RSA</strong> emitida pela AGT no <a href=":portal" target="_blank" class="underline font-bold">Portal do Contribuinte</a>.'
        => '<strong>What to configure here:</strong> The taxpayer NIF, the establishment code and the <strong>RSA private key</strong> issued by AGT on the <a href=":portal" target="_blank" class="underline font-bold">Taxpayer Portal</a>.',
    '= (Preço − Custo) / Custo' => '= (Price − Cost) / Cost',
    '= (Preço − Custo) / Preço &nbsp;•&nbsp;' => '= (Price − Cost) / Price &nbsp;•&nbsp;',
    'A, B, 01, etc' => 'A, B, 01, etc',
    'A, B, C, etc.' => 'A, B, C, etc.',
    'A = Série (personalizável)' => 'A = Series (customisable)',
    'Abrir POS' => 'Open POS',
    'Acesso API' => 'API Access',
    'A chave RSA é usada para assinar cada documento (<code>jwsDocumentSignature</code>) e cada requisição (<code>jwsSignature</code>). Os dados do software e as credenciais de acesso à API são <strong>globais</strong> e geridos pelo administrador.'
        => 'The RSA key is used to sign each document (<code>jwsDocumentSignature</code>) and each request (<code>jwsSignature</code>). The software details and API access credentials are <strong>global</strong> and managed by the administrator.',
    'A comunicar...' => 'Communicating...',
    'a configurar' => 'being configured',
    'Actividade económica (CAE)' => 'Economic activity (CAE)',
    'Activo' => 'Active',
    'Activos' => 'Active',
    'Acto' => 'Act',
    'Acto praticado em personificação' => 'Act carried out while impersonating',
    'A declarar à AGT:' => 'To be declared to AGT:',
    'Adiantamento (AD)' => 'Advance (AD)',
    'Adiantamento Automático:' => 'Automatic Advance:',
    'Adiantamentos (AD)' => 'Advances (AD)',
    'Adiantamento Usado:' => 'Advance Used:',
    'Adicionando...' => 'Adding...',
    'a emitir' => 'issuing',
    'A gerar XML...' => 'Generating XML...',
    'AGT → Produtor de Software' => 'AGT → Software Producer',
    'Aguardando início...' => 'Waiting to start...',
    'A guardar...' => 'Saving...',
    'A guia será marcada como anulada e removida da lista.' => 'The note will be marked as cancelled and removed from the list.',
    'Ajustes' => 'Adjustments',
    'Ajustes e transferências contam-se pelo número de ocorrências e não entram nas quantidades: num ajuste a quantidade registada é o saldo final e não uma variação, e uma transferência muda o artigo de armazém sem alterar o que a empresa tem.'
        => 'Adjustments and transfers are counted by number of occurrences and do not enter the quantities: in an adjustment the recorded quantity is the closing balance and not a change, and a transfer moves the item between warehouses without altering what the company holds.',
    'Alcance' => 'Scope',
    'Alerta (dias)' => 'Alert (days)',
    'Ambiente' => 'Environment',
    'Ambiente activo' => 'Active environment',
    'Ambiente AGT' => 'AGT Environment',
    'Ambientes' => 'Environments',
    'Ano' => 'Year',
    'Ano actual vs anterior' => 'Current year vs previous',
    'Ano da Série' => 'Series Year',
    'Antiguidade de saldos por faixa' => 'Balance ageing by band',
    'Antiguidade de saldos por faixa de dias' => 'Balance ageing by day band',
    'Anular' => 'Cancel',
    'Anular (reverte o stock)' => 'Cancel (reverses the stock)',
    'Análise de faturas de venda por período' => 'Analysis of sales invoices by period',
    'Análise de Margem por Produto' => 'Margin Analysis by Product',
    'Análise de variações período A vs período B' => 'Analysis of changes, period A vs period B',
    'Análise específica de serviços prestados' => 'Specific analysis of services provided',
    'Análises e mapas operacionais da gestão de faturação' => 'Analyses and operational reports for invoicing management',
    'AO-CAB — Cabinda (regime próprio)' => 'AO-CAB — Cabinda (own regime)',
    'AOA - Kwanza' => 'AOA - Kwanza',
    'AOA no período' => 'AOA in the period',
    'AO — Angola continental' => 'AO — Mainland Angola',
    'A Pagar' => 'Payable',
    'Aparência e Interface' => 'Appearance and Interface',
    'Apenas A Vencer' => 'Due Only',
    'Apenas Vencidas' => 'Overdue Only',
    'Aplicar IRT automaticamente em serviços' => 'Apply IRT automatically on services',
    'A preparar…' => 'Preparing…',
    'Aqui você apenas seleciona qual imposto usar como padrão em novos documentos.' => 'Here you only choose which tax to use as the default on new documents.',
    'Armazém *' => 'Warehouse *',
    'Armazém Destino' => 'Destination Warehouse',
    'Arquitectura de Chaves e Assinaturas AGT' => 'AGT Key and Signature Architecture',
    'Arredondamento' => 'Rounding',
    'Arredondamento:' => 'Rounding:',
    'As chaves pública e privada do Portal AGT são necessárias para assinar e submeter documentos desta empresa. Configure o par no separador <strong>Configurações</strong> acima.'
        => 'The public and private keys from the AGT Portal are needed to sign and submit this company\'s documents. Set up the pair under the <strong>Settings</strong> tab above.',
    'As configurações gerais de faturação (séries, impostos, descontos, etc.) aplicam-se também ao POS. Configure-as acima e salve para aplicar as mudanças.'
        => 'The general invoicing settings (series, taxes, discounts, etc.) apply to the POS as well. Set them above and save to apply the changes.',
    'As facturas de compra não se eliminam. Use "Anular" — reverte o stock e mantém o registo.'
        => 'Purchase invoices are not deleted. Use "Cancel" — it reverses the stock and keeps the record.',
    'A sincronizar...' => 'Syncing...',
    'Assinatura' => 'Signature',
    'A sua série (ex.: <span class="font-mono">FT A</span>) ligada ao código que a AGT lhe atribuiu (ex.: <span class="font-mono">FT7626S9153N</span>). É esse código que aparece no separador <em>Séries de facturas</em> do portal — o nome que deu à série cá dentro não é enviado à AGT.'
        => 'Your series (e.g. <span class="font-mono">FT A</span>) linked to the code AGT assigned to it (e.g. <span class="font-mono">FT7626S9153N</span>). That is the code shown on the portal\'s <em>Invoice series</em> tab — the name you gave the series in here is not sent to AGT.',
    'Atenção: existem faturas vencidas' => 'Warning: there are overdue invoices',
    'A testar...' => 'Testing...',
    'A trilha foi alterada fora da aplicação. Cada linha abaixo indica onde a cadeia parte.'
        => 'The trail was altered outside the application. Each line below shows where the chain breaks.',
    'Atualizar' => 'Refresh',
    'Atualizar estados AGT' => 'Refresh AGT statuses',
    'ausência de faturas vencidas' => 'absence of overdue invoices',
    'Auto-submissão' => 'Auto-submission',
    'Automática (província do cliente)' => 'Automatic (customer province)',
    'A validar...' => 'Validating...',
    'A Vencer' => 'Due',
    'A verificar...' => 'Checking...',
    'a ver o outro ambiente' => 'viewing the other environment',
    'Aviso:' => 'Warning:',
    'Ação irreversível' => 'Irreversible action',
    'Aéreo' => 'Air',
    'Base' => 'Base',
    'Basic Auth' => 'Basic Auth',
    'Bloqueia emissão se o documento não cumprir as regras de conformidade AGT v1.2.' => 'Blocks issuing if the document does not meet the AGT v1.2 compliance rules.',
    'Cabinda (AO-CAB) — regime próprio' => 'Cabinda (AO-CAB) — own regime',
    'Cada documento fiscal criado (FT/FR/NC/ND) é enviado automaticamente para a AGT após gravação.' => 'Each fiscal document created (FT/FR/NC/ND) is sent to AGT automatically once saved.',
    'Cadastrar Impostos' => 'Register Taxes',
    'Cadastre na Tesouraria' => 'Register under Treasury',
    'Cadeia íntegra' => 'Chain intact',
    'Caixa de Destino *' => 'Destination Cash Register *',
    'Campo' => 'Field',
    'Canal' => 'Channel',
    'Cartão de Crédito/Débito' => 'Credit/Debit Card',
    'Casas Decimais' => 'Decimal Places',
    'Categoria de Teste AGT' => 'AGT Test Category',
    'Chave privada do contribuinte removida.' => 'Taxpayer private key removed.',
    'Chave privada RSA (PEM)' => 'RSA private key (PEM)',
    'Chave privada RSA instalada com sucesso.' => 'RSA private key installed successfully.',
    'Chave pública RSA (PEM)' => 'RSA public key (PEM)',
    'Chave RSA' => 'RSA Key',
    'Chave RSA do <strong>contribuinte</strong>' => '<strong>Taxpayer</strong> RSA key',
    'Chave RSA do <strong>produtor</strong>' => '<strong>Producer</strong> RSA key',
    'Chaves do Portal AGT desta empresa' => 'AGT Portal keys for this company',
    'Chaves RSA' => 'RSA Keys',
    'Chaves RSA não configuradas' => 'RSA keys not configured',
    'Chave utilizada' => 'Key used',
    'Checklist de Conformidade' => 'Compliance Checklist',
    'Cliente *' => 'Customer *',
    'Cliente com NIF' => 'Customer with NIF',
    'Cliente identificado' => 'Identified customer',
    'Cliente Padrão (Consumidor Final)' => 'Default Customer (Final Consumer)',
    'Cliente sem NIF' => 'Customer without NIF',
    'Cole a chave privada PEM aqui:' => 'Paste the PEM private key here:',
    'Cole o par RSA fornecido no Portal do Contribuinte. As chaves são <strong>por empresa e por ambiente</strong> — o par abaixo é o de <strong>:ambiente</strong> e não afecta o outro ambiente.'
        => 'Paste the RSA pair supplied on the Taxpayer Portal. The keys are <strong>per company and per environment</strong> — the pair below is the one for <strong>:ambiente</strong> and does not affect the other environment.',
    'Comparativo Detalhado' => 'Detailed Comparison',
    'Comparativo entre Períodos' => 'Comparison Between Periods',
    'Completar venda automaticamente após pagamento' => 'Complete the sale automatically after payment',
    'Completo' => 'Complete',
    'Comportamento' => 'Behaviour',
    'Comportamento do Sistema' => 'System Behaviour',
    'Compras por período e fornecedor' => 'Purchases by period and supplier',
    'Comunicar à AGT' => 'Report to AGT',
    'Concluído' => 'Completed',
    'Conexão AGT estabelecida com sucesso.' => 'AGT connection established successfully.',
    'Conexão estabelecida com sucesso!' => 'Connection established successfully!',
    'Conexão OK.' => 'Connection OK.',
    'Configuração' => 'Configuration',
    'Configuração AGT (Facturação Electrónica)' => 'AGT Configuration (Electronic Invoicing)',
    'Configuração AGT guardada com sucesso.' => 'AGT configuration saved successfully.',
    'Configurações AGT Angola' => 'AGT Angola Settings',
    'Configurações AGT guardadas com sucesso!' => 'AGT settings saved successfully!',
    'Configurações Atuais' => 'Current Settings',
    'Configurações da Exportação' => 'Export Settings',
    'Configurações de Faturação' => 'Invoicing Settings',
    'Configurações do POS' => 'POS Settings',
    'Configurações salvas com sucesso!' => 'Settings saved successfully!',
    'Configure as séries e numeração dos documentos fiscais' => 'Set up the series and numbering of fiscal documents',
    'Configure o comportamento e aparência do Ponto de Venda.' => 'Set up the behaviour and appearance of the Point of Sale.',
    'Configure os dados do contribuinte para comunicar documentos fiscais à AGT.' => 'Set up the taxpayer details to report fiscal documents to AGT.',
    'Configure os dois. Escolher aqui só muda o que está a ver — a empresa continua a emitir pelo ambiente activo até o activar de propósito.'
        => 'Set up both. Choosing here only changes what you are looking at — the company keeps issuing through the active environment until you deliberately switch it.',
    'Configure os impostos conforme legislação angolana' => 'Set up taxes in line with Angolan law',
    'Configure os impostos primeiro' => 'Set up the taxes first',
    'Configure os padrões do sistema de faturação' => 'Set up the invoicing system defaults',
    'Confirmar e Adicionar' => 'Confirm and Add',
    'ConsultarFactura — consultar um documento emitido' => 'ConsultarFactura — look up an issued document',
    'Consultas seguras aos endpoints oficiais. RegistarFactura é executado apenas no fluxo de emissão de uma factura real.'
        => 'Safe queries to the official endpoints. RegistarFactura only runs in the flow that issues a real invoice.',
    'Conta' => 'Account',
    'Conta Bancária de Destino *' => 'Destination Bank Account *',
    'Contas Correntes' => 'Current Accounts',
    'Contexto' => 'Context',
    'Contexto de operação' => 'Operating context',
    'Controle e análise de produtos próximos da validade' => 'Control and analysis of products nearing expiry',
    'Correções SAFT-AO' => 'SAFT-AO Corrections',
    'Cotação' => 'Exchange rate',
    'Criar Fornecedor' => 'Create Supplier',
    'Criar Fornecedor Rápido' => 'Quick Create Supplier',
    'Crie a primeira série de documentos' => 'Create the first document series',
    'Crie a sua primeira fatura de compra' => 'Create your first purchase invoice',
    'Crie sua primeira importação para começar' => 'Create your first import to get started',
    'Crie séries em' => 'Create series under',
    'Critérios do Score (máximo 100 pontos):' => 'Score criteria (maximum 100 points):',
    'Crédito' => 'Credit',
    'Custo (CMV)' => 'Cost (COGS)',
    'Custo dos produtos vendidos' => 'Cost of goods sold',
    'Custo mais alto' => 'Highest cost',
    'Custo Total' => 'Total Cost',
    'Código CAE — Actividade Económica' => 'CAE Code — Economic Activity',
    'Código da Série' => 'Series Code',
    'Código da Série *' => 'Series Code *',
    'Código do estabelecimento registado no Portal do Contribuinte. Use "SEDE" se tiver apenas uma localização.'
        => 'Establishment code registered on the Taxpayer Portal. Use "SEDE" if you only have one location.',
    'Código no portal AGT' => 'Code on the AGT portal',
    'Código SAFT *' => 'SAFT Code *',
    'Dados a Incluir' => 'Data to Include',
    'Dados de Lote' => 'Batch Details',
    'Dados de lote atualizados!' => 'Batch details updated!',
    'Dados do Contribuinte' => 'Taxpayer Details',
    'Dados Fiscais AGT' => 'AGT Fiscal Details',
    'Data *' => 'Date *',
    'Data/Hora' => 'Date/Time',
    'Data/hora de carga' => 'Loading date/time',
    'Data de emissão *' => 'Issue date *',
    'Data de emissão:' => 'Issue date:',
    'Data de validade não informada' => 'Expiry date not given',
    'Data do Adiantamento *' => 'Advance Date *',
    'Data do Pedido' => 'Order Date',
    'Data final' => 'End date',
    'Data inicial' => 'Start date',
    'de 17 selecionados' => 'of 17 selected',
    'Decimais:' => 'Decimals:',
    'Decreto Presidencial n.º 71/25 — Sistema de Faturação Eletrónica' => 'Presidential Decree no. 71/25 — Electronic Invoicing System',
    'Definido pela legislação angolana' => 'Set by Angolan law',
    'Definir como série padrão' => 'Set as the default series',
    'Demonstração de Resultados' => 'Income Statement',
    'Demonstração de resultados completa' => 'Full income statement',
    'Demonstração de resultados do período' => 'Income statement for the period',
    'Desconto Máximo Permitido (%)' => 'Maximum Discount Allowed (%)',
    'Descrição (opcional)' => 'Description (optional)',
    'Descrição adicional (opcional)' => 'Additional description (optional)',
    'Descrição da série...' => 'Series description...',
    'Desembaraçado' => 'Cleared',
    'Desembaraço Pendente' => 'Clearance Pending',
    'Desempenho de vendas por utilizador (exclui canceladas/creditadas)' => 'Sales performance by user (excludes cancelled/credited)',
    'Despesas operacionais não modeladas (incluir manualmente na contabilidade)' => 'Operating expenses not modelled (include manually in accounting)',
    'Detalhe' => 'Detail',
    'Detalhe por Serviço' => 'Detail by Service',
    'Dias' => 'Days',
    'Dias de Alerta (antes da validade)' => 'Alert Days (before expiry)',
    'Dica' => 'Tip',
    'Distribuição' => 'Distribution',
    'Doc. motorista' => 'Driver doc.',
    'Docs' => 'Docs',
    'Documento, artigo ou pessoa...' => 'Document, item or person...',
    'Documento Conforme AGT' => 'AGT-Compliant Document',
    'Documento não encontrado' => 'Document not found',
    'Documento não fiscal; não é enviado à AGT.' => 'Non-fiscal document; it is not sent to AGT.',
    'Documento Rectificado' => 'Rectified Document',
    'Documento reenviado com sucesso!' => 'Document resent successfully!',
    'Documentos de transporte de mercadorias (GT / GR)' => 'Goods transport documents (GT / GR)',
    'Documentos enviados, validados ou rejeitados pela AGT' => 'Documents sent, validated or rejected by AGT',
    'Documento validado para conformidade AGT!' => 'Document validated for AGT compliance!',
    'DS.120 §4.6: A=Aberta, U=Em utilização, F=Fechada' => 'DS.120 §4.6: A=Open, U=In use, F=Closed',
    'Débito' => 'Debit',
    'Eliminar Adiantamento?' => 'Delete Advance?',
    'Eliminar Série?' => 'Delete Series?',
    'Emails (CSV)' => 'Emails (CSV)',
    'Emissão' => 'Issue',
    'Emitido por:' => 'Issued by:',
    'Empresa activa:' => 'Active company:',
    'Empresas diferentes.' => 'Different companies.',
    'Em Trânsito' => 'In Transit',
    'Entradas' => 'Inflows',
    'entre armazéns' => 'between warehouses',
    'Enviar documentos automaticamente à AGT' => 'Send documents to AGT automatically',
    'Erro: :detalhe' => 'Error: :detalhe',
    'Erro ao abrir modal: :detalhe' => 'Error opening the dialog: :detalhe',
    'Erro ao anular: :detalhe' => 'Error cancelling: :detalhe',
    'Erro ao atualizar fatura: :detalhe' => 'Error updating the invoice: :detalhe',
    'Erro ao converter: :detalhe' => 'Error converting: :detalhe',
    'Erro ao eliminar série: :detalhe' => 'Error deleting the series: :detalhe',
    'Erro ao gerar SAFT: :detalhe' => 'Error generating the SAFT: :detalhe',
    'Erro ao limpar documentos: :detalhe' => 'Error clearing documents: :detalhe',
    'Erro ao salvar fatura: :detalhe' => 'Error saving the invoice: :detalhe',
    'Erro ao salvar proforma: :detalhe' => 'Error saving the proforma: :detalhe',
    'Erro de validação: :detalhe' => 'Validation error: :detalhe',
    'Escopo' => 'Scope',
    'Esta ação não pode ser desfeita! Todos os dados relacionados serão permanentemente eliminados.'
        => 'This action cannot be undone! All related data will be permanently deleted.',
    'Estabelecimento' => 'Establishment',
    'Estabelecimento *' => 'Establishment *',
    'Esta chave é <strong>gerada e emitida pela AGT</strong> e está disponível no <a href=":portal" target="_blank" class="underline font-bold">Portal do Contribuinte</a>. É utilizada para assinar digitalmente cada documento (<code>jwsDocumentSignature</code>) e cada requisição (<code>jwsSignature</code>). <strong>Nunca partilhe esta chave.</strong>'
        => 'This key is <strong>generated and issued by AGT</strong> and is available on the <a href=":portal" target="_blank" class="underline font-bold">Taxpayer Portal</a>. It is used to digitally sign each document (<code>jwsDocumentSignature</code>) and each request (<code>jwsSignature</code>). <strong>Never share this key.</strong>',
    'Estado:' => 'Status:',
    'Estado AGT' => 'AGT Status',
    'Estado SAFT' => 'SAFT Status',
    'Esta fatura já está anulada.' => 'This invoice is already cancelled.',
    'Estas credenciais são globais do <strong>produtor de software</strong> — não do contribuinte.'
        => 'These credentials belong globally to the <strong>software producer</strong> — not to the taxpayer.',
    'Esta semana' => 'This week',
    'Este mês' => 'This month',
    'Estes campos só são usados ao registar a série na AGT (`SolicitarSerie`).' => 'These fields are only used when registering the series with AGT (`SolicitarSerie`).',
    'Estrutura do XML' => 'XML Structure',
    'ETA (Prev. Chegada)' => 'ETA (Est. Arrival)',
    'EUR - Euro' => 'EUR - Euro',
    'Evolução dos Últimos 6 Meses' => 'Trend Over the Last 6 Months',
    'Ex.: 5001636863' => 'e.g. 5001636863',
    'Ex.: China' => 'e.g. China',
    'Ex.: FT A/2026/000001' => 'e.g. FT A/2026/000001',
    'Ex.: PO-2025-001' => 'e.g. PO-2025-001',
    'Ex.: Shanghai' => 'e.g. Shanghai',
    'Ex: IVA14' => 'e.g. IVA14',
    'Ex: IVA 14% Normal' => 'e.g. VAT 14% Standard',
    'Ex: LOTE-2025-001 ou deixe vazio para gerar automaticamente' => 'e.g. BATCH-2025-001, or leave empty to generate automatically',
    'Ex: Nº comprovante...' => 'e.g. Proof no....',
    'Ex: Pagamento antecipado...' => 'e.g. Advance payment...',
    'Ex: Vendas Loja, Vendas Online' => 'e.g. Shop Sales, Online Sales',
    'Ex: Vendas Loja, Vendas Online...' => 'e.g. Shop Sales, Online Sales...',
    'Executar consulta' => 'Run query',
    'Execute o seeder para criar os impostos de Angola' => 'Run the seeder to create the Angolan taxes',
    'Exemplo:' => 'Example:',
    'Exemplo: A, B, C, 01, 02, etc.' => 'Example: A, B, C, 01, 02, etc.',
    'Exemplo atual:' => 'Current example:',
    'Exigir cliente em todas as vendas' => 'Require a customer on every sale',
    'Exigir validação AGT antes de imprimir' => 'Require AGT validation before printing',
    'Exigir validação prévia' => 'Require prior validation',
    'Existem faturas com pagamento vencido' => 'There are invoices with overdue payment',
    'Expira em 7 dias' => 'Expires in 7 days',
    'Expira em 30 dias' => 'Expires in 30 days',
    'Expirando em Breve' => 'Expiring Soon',
    'Exportar' => 'Export',
    'Exportar CSV' => 'Export CSV',
    'Exportação em desenvolvimento...' => 'Export under development...',
    'Expressão (Art. 12º)' => 'Wording (Art. 12)',
    'Factura anulada — o registo mantém-se por exigência fiscal' => 'Invoice cancelled — the record is kept as required by tax law',
    'Factura de origem' => 'Source invoice',
    'Facturação Electrónica AGT' => 'AGT Electronic Invoicing',
    'Falha na conexão' => 'Connection failed',
    'Falhou.' => 'Failed.',
    'Fatura-Recibo POS (FR)' => 'POS Invoice-Receipt (FR)',
    'Fatura de Compra (FC)' => 'Purchase Invoice (FC)',
    'Fatura de compra anulada. O stock foi revertido.' => 'Purchase invoice cancelled. The stock has been reversed.',
    'Fatura de origem (opcional)' => 'Source invoice (optional)',
    'Faturas (FT)' => 'Invoices (FT)',
    'Faturas:' => 'Invoices:',
    'faturas com serviços' => 'invoices with services',
    'Faturas de Compra' => 'Purchase Invoices',
    'Faturas de Compra (FC)' => 'Purchase Invoices (FC)',
    'Faturas de compra pendentes' => 'Pending purchase invoices',
    'Faturas de compra por período' => 'Purchase invoices by period',
    'Faturas de venda pendentes' => 'Pending sales invoices',
    'Faturas e compras de fornecedores' => 'Supplier invoices and purchases',
    'Faturas no Período' => 'Invoices in the Period',
    'Faturas pendentes a fornecedores' => 'Invoices pending to suppliers',
    'Faturas pendentes de clientes' => 'Invoices pending from customers',
    'Faturação → Séries de Documentos' => 'Invoicing → Document Series',
    'FEPC — Pré-Comunicada' => 'FEPC — Pre-reported',
    'Ferramentas API' => 'API Tools',
    'FESF — Sem Facturação' => 'FESF — No Invoicing',
    'Fiabilidade' => 'Reliability',
    'Fiabilidade (25 pts):' => 'Reliability (25 pts):',
    'Fiabilidade:' => 'Reliability:',
    'Filtrar por Tipo' => 'Filter by Type',
    'Filtro' => 'Filter',
    'Finalidade' => 'Purpose',
    'Fiscal & SAFT' => 'Fiscal & SAFT',
    'FOB + Frete + Seguro' => 'FOB + Freight + Insurance',
    'Formato:' => 'Format:',
    'Formato AGT Angola' => 'AGT Angola Format',
    'Formato de Números e Decimais' => 'Number and Decimal Format',
    'Formato PEM, RSA mínimo 2048 bits. Armazenada localmente no servidor (não na BD).' => 'PEM format, RSA at least 2048 bits. Stored locally on the server (not in the database).',
    'Fornecedor *' => 'Supplier *',
    'Fornecedor criado com sucesso: :detalhe' => 'Supplier created successfully: :detalhe',
    'Fornecedor selecionado: :detalhe' => 'Supplier selected: :detalhe',
    'FR = Fatura-Recibo (fixo)' => 'FR = Invoice-Receipt (fixed)',
    'FR A' => 'FR A',
    'Frequência (20 pts):' => 'Frequency (20 pts):',
    'Frete' => 'Freight',
    'FT, FR, PR, RC, NC, ND, FC, AD' => 'FT, FR, PR, RC, NC, ND, FC, AD',
    'FT A 2025/000001' => 'FT A 2025/000001',
    'Gerador de Documentos AGT Angola' => 'AGT Angola Document Generator',
    'Gerar Documentos' => 'Generate Documents',
    'Gerar e Baixar SAFT-AO' => 'Generate and Download SAFT-AO',
    'Gerar PDF' => 'Generate PDF',
    'Gere documentos de teste conforme Decreto Presidencial 312/18' => 'Generate test documents under Presidential Decree 312/18',
    'Gerir impostos' => 'Manage taxes',
    'Gerir Impostos' => 'Manage Taxes',
    'Gestão completa do processo de importação - Angola' => 'Full management of the import process - Angola',
    'Gestão de Impostos' => 'Tax Management',
    'Gestão de Impostos (IVA)' => 'Tax Management (VAT)',
    'Gestão de Séries de Documentos' => 'Document Series Management',
    'Global' => 'Global',
    'Guardar configuração' => 'Save configuration',
    'Guardar Configurações' => 'Save Settings',
    'Guia de Remessa' => 'Delivery Note',
    'Guia de Transporte' => 'Transport Note',
    'Guia de Transporte (GT)' => 'Transport Note (GT)',
    'Guias de Transporte (GT)' => 'Transport Notes (GT)',
    'Guias de Transporte / Remessa' => 'Transport / Delivery Notes',
    'Hash' => 'Hash',
    'Hash presente:' => 'Hash present:',
    'Hash SAFT' => 'SAFT Hash',
    'Histórico de Submissões FE' => 'E-Invoicing Submission History',
    'Hoje' => 'Today',
    'Homologação' => 'Sandbox',
    'Homologação (sandbox)' => 'Sandbox',
    'Importante' => 'Important',
    'Importações de Mercadorias' => 'Goods Imports',
    'Imposto padrão' => 'Default tax',
    'Imposto Padrão (IVA)' => 'Default Tax (VAT)',
    'Impostos' => 'Taxes',
    'Impostos Disponíveis' => 'Available Taxes',
    'Impostos e Retenções' => 'Taxes and Withholdings',
    'Impressão' => 'Printing',
    'Imprimir automaticamente após salvar' => 'Print automatically after saving',
    'Imprimir automaticamente após venda' => 'Print automatically after a sale',
    'Inactivo' => 'Inactive',
    'Inactivos' => 'Inactive',
    'Incluir ano no formato (FT A/2025/000001)' => 'Include the year in the format (FT A/2025/000001)',
    'Indicador' => 'Indicator',
    'Informações do Adiantamento' => 'Advance Details',
    'Informações do Fornecedor' => 'Supplier Details',
    'Inspeção Alfandegária' => 'Customs Inspection',
    'instalada' => 'installed',
    'Instale primeiro o par RSA de Produção do Portal do Contribuinte. Sem ele nenhum documento é assinado.'
        => 'Install the Production RSA pair from the Taxpayer Portal first. Without it no document is signed.',
    'Internacional - 20,000.00' => 'International - 20,000.00',
    'inventário corrigido' => 'inventory corrected',
    'ISE - Isento' => 'ISE - Exempt',
    'IVA Dedutível (Compras)' => 'Deductible VAT (Purchases)',
    'IVA Dedutível por Taxa' => 'Deductible VAT by Rate',
    'IVA Liquidado (Vendas)' => 'Output VAT (Sales)',
    'IVA liquidado, dedutível e a entregar' => 'Output, deductible and payable VAT',
    'IVA liquidado, dedutível e a pagar' => 'Output, deductible and payable VAT',
    'IVA Liquidado por Taxa' => 'Output VAT by Rate',
    'Jan–15Dez: ano corrente. Após 15Dez: corrente ou seguinte.' => 'Jan–15 Dec: current year. After 15 Dec: current or next.',
    'Já Expirados' => 'Already Expired',
    'Já Pago' => 'Already Paid',
    'Já é este o ambiente activo.' => 'This is already the active environment.',
    'Limite' => 'Limit',
    'Limpar Todos os Documentos' => 'Clear All Documents',
    'Links Rápidos' => 'Quick Links',
    'Liquidado − Dedutível' => 'Output − Deductible',
    'Lista de emails (separados por vírgula) que recebem notificação quando uma submissão à AGT é <strong>rejeitada</strong> (resultCode 2) ou contém <strong>erros parciais</strong> (resultCode 1). Se vazio, é usado o fallback dos utilizadores com permissão <code class="bg-amber-100 px-1 rounded">invoicing.agt.view</code>.'
        => 'List of emails (comma-separated) notified when an AGT submission is <strong>rejected</strong> (resultCode 2) or contains <strong>partial errors</strong> (resultCode 1). If empty, the fallback is the users holding the <code class="bg-amber-100 px-1 rounded">invoicing.agt.view</code> permission.',
    'Lista de Faturas de Compra' => 'Purchase Invoice List',
    'ListarFacturas — documentos RECEBIDOS (empresa como adquirente)' => 'ListarFacturas — RECEIVED documents (company as buyer)',
    'Local de carga' => 'Loading place',
    'Local de descarga' => 'Unloading place',
    'Logs' => 'Logs',
    'Logs de Comunicação' => 'Communication Logs',
    'Logística & Transporte' => 'Logistics & Transport',
    'Lote/Validade' => 'Batch/Expiry',
    'Luanda' => 'Luanda',
    'Lucro' => 'Profit',
    'Lucro/prejuízo por produto vendido' => 'Profit/loss per product sold',
    'Lucro e margem por produto' => 'Profit and margin by product',
    'Lucro Unit.' => 'Unit Profit',
    'Maior lucro' => 'Highest profit',
    'Maior margem' => 'Highest margin',
    'Maior margem %' => 'Highest margin %',
    'Maior prejuízo' => 'Biggest loss',
    'Maior receita' => 'Highest revenue',
    'Maior rotação' => 'Highest turnover',
    'Mais vendidos' => 'Best sellers',
    'Marcar como Conforme' => 'Mark as Compliant',
    'Margem' => 'Margin',
    'Margem %' => 'Margin %',
    'Margem:' => 'Margin:',
    'Margem Média' => 'Average Margin',
    'Margem Negativa' => 'Negative Margin',
    'Markup' => 'Markup',
    'Markup %' => 'Markup %',
    'Marque todos os itens do checklist antes de aprovar' => 'Tick every checklist item before approving',
    'Marítimo' => 'Sea',
    'Matrícula da viatura' => 'Vehicle registration',
    'MB Way' => 'MB Way',
    'Meio' => 'Method',
    'Meio para cima (0,5+)' => 'Half up (0.5+)',
    'Menor margem %' => 'Lowest margin %',
    'Menor stock' => 'Lowest stock',
    'Mensagem AGT visível' => 'AGT message visible',
    'Modo' => 'Mode',
    'Moeda:' => 'Currency:',
    'Moeda Padrão' => 'Default Currency',
    'Mostrar imagens dos produtos' => 'Show product images',
    'Mostrar logótipo da empresa' => 'Show the company logo',
    'Motorista' => 'Driver',
];

$fr = [
    '% do Total' => '% du total',
    '(+) Receita Bruta de Vendas' => '(+) Chiffre d\'affaires brut',
    '(=) Receita Líquida' => '(=) Chiffre d\'affaires net',
    '(DS.120 §4.1)' => '(DS.120 §4.1)',
    '(DS.120 §4.5)' => '(DS.120 §4.5)',
    '(DS.120 §4.6)' => '(DS.120 §4.6)',
    '(vai no payload da AGT)' => '(transmis dans le payload AGT)',
    '(−) Custo dos Produtos Vendidos (CMV)' => '(−) Coût des marchandises vendues (CMV)',
    '(−) Descontos concedidos' => '(−) Remises accordées',
    '(−) Devoluções (Notas de Crédito)' => '(−) Retours (avoirs)',
    '+120 dias' => '+120 jours',
    '0 decimais - 20.000' => '0 décimale - 20 000',
    '000001 = Numeração sequencial' => '000001 = Numérotation séquentielle',
    '1 decimal - 20.000,0' => '1 décimale - 20 000,0',
    '1-30 dias' => '1-30 jours',
    '2 decimais - 20.000,00' => '2 décimales - 20 000,00',
    '3 decimais - 20.000,000' => '3 décimales - 20 000,000',
    '4 decimais - 20.000,0000' => '4 décimales - 20 000,0000',
    '7 dias' => '7 jours',
    '8 produtos' => '8 produits',
    '12 produtos' => '12 produits',
    '15 dias' => '15 jours',
    '16 produtos' => '16 produits',
    '20 produtos' => '20 produits',
    '24 produtos' => '24 produits',
    '25 por página' => '25 par page',
    '31-60 dias' => '31-60 jours',
    '50 por página' => '50 par page',
    '60 dias' => '60 jours',
    '61-90 dias' => '61-90 jours',
    '91-120 dias' => '91-120 jours',
    '100 por página' => '100 par page',
    '<strong>Credenciais do produtor não configuradas.</strong> O administrador do sistema precisa configurar as credenciais Basic Auth (username/password) em <strong>Operação AGT → Configurações</strong> para que a comunicação com a API AGT funcione.'
        => '<strong>Identifiants du producteur non configurés.</strong> L\'administrateur du système doit configurer les identifiants Basic Auth (nom d\'utilisateur/mot de passe) dans <strong>Opération AGT → Paramètres</strong> pour que la communication avec l\'API AGT fonctionne.',
    '<strong>O que configurar aqui:</strong> O NIF do contribuinte, o código do estabelecimento e a <strong>chave privada RSA</strong> emitida pela AGT no <a href=":portal" target="_blank" class="underline font-bold">Portal do Contribuinte</a>.'
        => '<strong>Ce qu\'il faut configurer ici :</strong> le NIF du contribuable, le code de l\'établissement et la <strong>clé privée RSA</strong> délivrée par l\'AGT sur le <a href=":portal" target="_blank" class="underline font-bold">Portail du contribuable</a>.',
    '= (Preço − Custo) / Custo' => '= (Prix − Coût) / Coût',
    '= (Preço − Custo) / Preço &nbsp;•&nbsp;' => '= (Prix − Coût) / Prix &nbsp;•&nbsp;',
    'A, B, 01, etc' => 'A, B, 01, etc',
    'A, B, C, etc.' => 'A, B, C, etc.',
    'A = Série (personalizável)' => 'A = Série (personnalisable)',
    'Abrir POS' => 'Ouvrir le POS',
    'Acesso API' => 'Accès API',
    'A chave RSA é usada para assinar cada documento (<code>jwsDocumentSignature</code>) e cada requisição (<code>jwsSignature</code>). Os dados do software e as credenciais de acesso à API são <strong>globais</strong> e geridos pelo administrador.'
        => 'La clé RSA sert à signer chaque document (<code>jwsDocumentSignature</code>) et chaque requête (<code>jwsSignature</code>). Les données du logiciel et les identifiants d\'accès à l\'API sont <strong>globaux</strong> et gérés par l\'administrateur.',
    'A comunicar...' => 'Communication...',
    'a configurar' => 'en configuration',
    'Actividade económica (CAE)' => 'Activité économique (CAE)',
    'Activo' => 'Actif',
    'Activos' => 'Actifs',
    'Acto' => 'Acte',
    'Acto praticado em personificação' => 'Acte réalisé en usurpation d\'identité',
    'A declarar à AGT:' => 'À déclarer à l\'AGT :',
    'Adiantamento (AD)' => 'Acompte (AD)',
    'Adiantamento Automático:' => 'Acompte automatique :',
    'Adiantamentos (AD)' => 'Acomptes (AD)',
    'Adiantamento Usado:' => 'Acompte utilisé :',
    'Adicionando...' => 'Ajout...',
    'a emitir' => 'en émission',
    'A gerar XML...' => 'Génération du XML...',
    'AGT → Produtor de Software' => 'AGT → Producteur de logiciel',
    'Aguardando início...' => 'En attente de démarrage...',
    'A guardar...' => 'Enregistrement...',
    'A guia será marcada como anulada e removida da lista.' => 'Le bon sera marqué comme annulé et retiré de la liste.',
    'Ajustes' => 'Ajustements',
    'Ajustes e transferências contam-se pelo número de ocorrências e não entram nas quantidades: num ajuste a quantidade registada é o saldo final e não uma variação, e uma transferência muda o artigo de armazém sem alterar o que a empresa tem.'
        => 'Les ajustements et transferts sont comptés en nombre d\'occurrences et n\'entrent pas dans les quantités : dans un ajustement, la quantité enregistrée est le solde final et non une variation, et un transfert déplace l\'article d\'un entrepôt à l\'autre sans changer ce que l\'entreprise détient.',
    'Alcance' => 'Portée',
    'Alerta (dias)' => 'Alerte (jours)',
    'Ambiente' => 'Environnement',
    'Ambiente activo' => 'Environnement actif',
    'Ambiente AGT' => 'Environnement AGT',
    'Ambientes' => 'Environnements',
    'Ano' => 'Année',
    'Ano actual vs anterior' => 'Année en cours vs précédente',
    'Ano da Série' => 'Année de la série',
    'Antiguidade de saldos por faixa' => 'Balance âgée par tranche',
    'Antiguidade de saldos por faixa de dias' => 'Balance âgée par tranche de jours',
    'Anular' => 'Annuler',
    'Anular (reverte o stock)' => 'Annuler (inverse le stock)',
    'Análise de faturas de venda por período' => 'Analyse des factures de vente par période',
    'Análise de Margem por Produto' => 'Analyse de marge par produit',
    'Análise de variações período A vs período B' => 'Analyse des écarts période A vs période B',
    'Análise específica de serviços prestados' => 'Analyse spécifique des services rendus',
    'Análises e mapas operacionais da gestão de faturação' => 'Analyses et états opérationnels de la gestion de facturation',
    'AO-CAB — Cabinda (regime próprio)' => 'AO-CAB — Cabinda (régime propre)',
    'AOA - Kwanza' => 'AOA - Kwanza',
    'AOA no período' => 'AOA sur la période',
    'AO — Angola continental' => 'AO — Angola continental',
    'A Pagar' => 'À payer',
    'Aparência e Interface' => 'Apparence et interface',
    'Apenas A Vencer' => 'À échoir uniquement',
    'Apenas Vencidas' => 'Échues uniquement',
    'Aplicar IRT automaticamente em serviços' => 'Appliquer l\'IRT automatiquement sur les services',
    'A preparar…' => 'Préparation…',
    'Aqui você apenas seleciona qual imposto usar como padrão em novos documentos.' => 'Ici vous choisissez seulement quelle taxe utiliser par défaut sur les nouveaux documents.',
    'Armazém *' => 'Entrepôt *',
    'Armazém Destino' => 'Entrepôt de destination',
    'Arquitectura de Chaves e Assinaturas AGT' => 'Architecture des clés et signatures AGT',
    'Arredondamento' => 'Arrondi',
    'Arredondamento:' => 'Arrondi :',
    'As chaves pública e privada do Portal AGT são necessárias para assinar e submeter documentos desta empresa. Configure o par no separador <strong>Configurações</strong> acima.'
        => 'Les clés publique et privée du Portail AGT sont nécessaires pour signer et soumettre les documents de cette entreprise. Configurez la paire dans l\'onglet <strong>Paramètres</strong> ci-dessus.',
    'As configurações gerais de faturação (séries, impostos, descontos, etc.) aplicam-se também ao POS. Configure-as acima e salve para aplicar as mudanças.'
        => 'Les paramètres généraux de facturation (séries, taxes, remises, etc.) s\'appliquent aussi au POS. Configurez-les ci-dessus et enregistrez pour appliquer les changements.',
    'As facturas de compra não se eliminam. Use "Anular" — reverte o stock e mantém o registo.'
        => 'Les factures d\'achat ne se suppriment pas. Utilisez « Annuler » — cela inverse le stock et conserve l\'enregistrement.',
    'A sincronizar...' => 'Synchronisation...',
    'Assinatura' => 'Signature',
    'A sua série (ex.: <span class="font-mono">FT A</span>) ligada ao código que a AGT lhe atribuiu (ex.: <span class="font-mono">FT7626S9153N</span>). É esse código que aparece no separador <em>Séries de facturas</em> do portal — o nome que deu à série cá dentro não é enviado à AGT.'
        => 'Votre série (ex. : <span class="font-mono">FT A</span>) liée au code que l\'AGT lui a attribué (ex. : <span class="font-mono">FT7626S9153N</span>). C\'est ce code qui apparaît dans l\'onglet <em>Séries de factures</em> du portail — le nom que vous avez donné à la série ici n\'est pas transmis à l\'AGT.',
    'Atenção: existem faturas vencidas' => 'Attention : il existe des factures échues',
    'A testar...' => 'Test en cours...',
    'A trilha foi alterada fora da aplicação. Cada linha abaixo indica onde a cadeia parte.'
        => 'La piste a été modifiée hors de l\'application. Chaque ligne ci-dessous indique où la chaîne est rompue.',
    'Atualizar' => 'Actualiser',
    'Atualizar estados AGT' => 'Actualiser les statuts AGT',
    'ausência de faturas vencidas' => 'absence de factures échues',
    'Auto-submissão' => 'Soumission automatique',
    'Automática (província do cliente)' => 'Automatique (province du client)',
    'A validar...' => 'Validation...',
    'A Vencer' => 'À échoir',
    'A verificar...' => 'Vérification...',
    'a ver o outro ambiente' => 'consultation de l\'autre environnement',
    'Aviso:' => 'Avertissement :',
    'Ação irreversível' => 'Action irréversible',
    'Aéreo' => 'Aérien',
    'Base' => 'Base',
    'Basic Auth' => 'Basic Auth',
    'Bloqueia emissão se o documento não cumprir as regras de conformidade AGT v1.2.' => 'Bloque l\'émission si le document ne respecte pas les règles de conformité AGT v1.2.',
    'Cabinda (AO-CAB) — regime próprio' => 'Cabinda (AO-CAB) — régime propre',
    'Cada documento fiscal criado (FT/FR/NC/ND) é enviado automaticamente para a AGT após gravação.' => 'Chaque document fiscal créé (FT/FR/NC/ND) est envoyé automatiquement à l\'AGT après enregistrement.',
    'Cadastrar Impostos' => 'Enregistrer les taxes',
    'Cadastre na Tesouraria' => 'Enregistrez dans Trésorerie',
    'Cadeia íntegra' => 'Chaîne intacte',
    'Caixa de Destino *' => 'Caisse de destination *',
    'Campo' => 'Champ',
    'Canal' => 'Canal',
    'Cartão de Crédito/Débito' => 'Carte de crédit/débit',
    'Casas Decimais' => 'Décimales',
    'Categoria de Teste AGT' => 'Catégorie de test AGT',
    'Chave privada do contribuinte removida.' => 'Clé privée du contribuable supprimée.',
    'Chave privada RSA (PEM)' => 'Clé privée RSA (PEM)',
    'Chave privada RSA instalada com sucesso.' => 'Clé privée RSA installée avec succès.',
    'Chave pública RSA (PEM)' => 'Clé publique RSA (PEM)',
    'Chave RSA' => 'Clé RSA',
    'Chave RSA do <strong>contribuinte</strong>' => 'Clé RSA du <strong>contribuable</strong>',
    'Chave RSA do <strong>produtor</strong>' => 'Clé RSA du <strong>producteur</strong>',
    'Chaves do Portal AGT desta empresa' => 'Clés du Portail AGT de cette entreprise',
    'Chaves RSA' => 'Clés RSA',
    'Chaves RSA não configuradas' => 'Clés RSA non configurées',
    'Chave utilizada' => 'Clé utilisée',
    'Checklist de Conformidade' => 'Liste de conformité',
    'Cliente *' => 'Client *',
    'Cliente com NIF' => 'Client avec NIF',
    'Cliente identificado' => 'Client identifié',
    'Cliente Padrão (Consumidor Final)' => 'Client par défaut (consommateur final)',
    'Cliente sem NIF' => 'Client sans NIF',
    'Cole a chave privada PEM aqui:' => 'Collez la clé privée PEM ici :',
    'Cole o par RSA fornecido no Portal do Contribuinte. As chaves são <strong>por empresa e por ambiente</strong> — o par abaixo é o de <strong>:ambiente</strong> e não afecta o outro ambiente.'
        => 'Collez la paire RSA fournie sur le Portail du contribuable. Les clés sont <strong>par entreprise et par environnement</strong> — la paire ci-dessous est celle de <strong>:ambiente</strong> et n\'affecte pas l\'autre environnement.',
    'Comparativo Detalhado' => 'Comparatif détaillé',
    'Comparativo entre Períodos' => 'Comparatif entre périodes',
    'Completar venda automaticamente após pagamento' => 'Finaliser la vente automatiquement après paiement',
    'Completo' => 'Complet',
    'Comportamento' => 'Comportement',
    'Comportamento do Sistema' => 'Comportement du système',
    'Compras por período e fornecedor' => 'Achats par période et fournisseur',
    'Comunicar à AGT' => 'Déclarer à l\'AGT',
    'Concluído' => 'Terminé',
    'Conexão AGT estabelecida com sucesso.' => 'Connexion AGT établie avec succès.',
    'Conexão estabelecida com sucesso!' => 'Connexion établie avec succès !',
    'Conexão OK.' => 'Connexion OK.',
    'Configuração' => 'Configuration',
    'Configuração AGT (Facturação Electrónica)' => 'Configuration AGT (facturation électronique)',
    'Configuração AGT guardada com sucesso.' => 'Configuration AGT enregistrée avec succès.',
    'Configurações AGT Angola' => 'Paramètres AGT Angola',
    'Configurações AGT guardadas com sucesso!' => 'Paramètres AGT enregistrés avec succès !',
    'Configurações Atuais' => 'Paramètres actuels',
    'Configurações da Exportação' => 'Paramètres de l\'export',
    'Configurações de Faturação' => 'Paramètres de facturation',
    'Configurações do POS' => 'Paramètres du POS',
    'Configurações salvas com sucesso!' => 'Paramètres enregistrés avec succès !',
    'Configure as séries e numeração dos documentos fiscais' => 'Configurez les séries et la numérotation des documents fiscaux',
    'Configure o comportamento e aparência do Ponto de Venda.' => 'Configurez le comportement et l\'apparence du point de vente.',
    'Configure os dados do contribuinte para comunicar documentos fiscais à AGT.' => 'Configurez les données du contribuable pour déclarer les documents fiscaux à l\'AGT.',
    'Configure os dois. Escolher aqui só muda o que está a ver — a empresa continua a emitir pelo ambiente activo até o activar de propósito.'
        => 'Configurez les deux. Choisir ici ne change que ce que vous consultez — l\'entreprise continue d\'émettre via l\'environnement actif jusqu\'à ce que vous l\'activiez délibérément.',
    'Configure os impostos conforme legislação angolana' => 'Configurez les taxes conformément à la législation angolaise',
    'Configure os impostos primeiro' => 'Configurez d\'abord les taxes',
    'Configure os padrões do sistema de faturação' => 'Configurez les valeurs par défaut du système de facturation',
    'Confirmar e Adicionar' => 'Confirmer et ajouter',
    'ConsultarFactura — consultar um documento emitido' => 'ConsultarFactura — consulter un document émis',
    'Consultas seguras aos endpoints oficiais. RegistarFactura é executado apenas no fluxo de emissão de uma factura real.'
        => 'Consultations sûres des endpoints officiels. RegistarFactura n\'est exécuté que dans le flux d\'émission d\'une facture réelle.',
    'Conta' => 'Compte',
    'Conta Bancária de Destino *' => 'Compte bancaire de destination *',
    'Contas Correntes' => 'Comptes courants',
    'Contexto' => 'Contexte',
    'Contexto de operação' => 'Contexte d\'exploitation',
    'Controle e análise de produtos próximos da validade' => 'Contrôle et analyse des produits proches de la péremption',
    'Correções SAFT-AO' => 'Corrections SAFT-AO',
    'Cotação' => 'Taux de change',
    'Criar Fornecedor' => 'Créer un fournisseur',
    'Criar Fornecedor Rápido' => 'Création rapide de fournisseur',
    'Crie a primeira série de documentos' => 'Créez la première série de documents',
    'Crie a sua primeira fatura de compra' => 'Créez votre première facture d\'achat',
    'Crie sua primeira importação para começar' => 'Créez votre première importation pour commencer',
    'Crie séries em' => 'Créez des séries dans',
    'Critérios do Score (máximo 100 pontos):' => 'Critères du score (maximum 100 points) :',
    'Crédito' => 'Crédit',
    'Custo (CMV)' => 'Coût (CMV)',
    'Custo dos produtos vendidos' => 'Coût des marchandises vendues',
    'Custo mais alto' => 'Coût le plus élevé',
    'Custo Total' => 'Coût total',
    'Código CAE — Actividade Económica' => 'Code CAE — Activité économique',
    'Código da Série' => 'Code de la série',
    'Código da Série *' => 'Code de la série *',
    'Código do estabelecimento registado no Portal do Contribuinte. Use "SEDE" se tiver apenas uma localização.'
        => 'Code de l\'établissement enregistré sur le Portail du contribuable. Utilisez « SEDE » si vous n\'avez qu\'un seul site.',
    'Código no portal AGT' => 'Code sur le portail AGT',
    'Código SAFT *' => 'Code SAFT *',
    'Dados a Incluir' => 'Données à inclure',
    'Dados de Lote' => 'Données du lot',
    'Dados de lote atualizados!' => 'Données du lot mises à jour !',
    'Dados do Contribuinte' => 'Données du contribuable',
    'Dados Fiscais AGT' => 'Données fiscales AGT',
    'Data *' => 'Date *',
    'Data/Hora' => 'Date/Heure',
    'Data/hora de carga' => 'Date/heure de chargement',
    'Data de emissão *' => 'Date d\'émission *',
    'Data de emissão:' => 'Date d\'émission :',
    'Data de validade não informada' => 'Date de péremption non renseignée',
    'Data do Adiantamento *' => 'Date de l\'acompte *',
    'Data do Pedido' => 'Date de la commande',
    'Data final' => 'Date de fin',
    'Data inicial' => 'Date de début',
    'de 17 selecionados' => 'sur 17 sélectionnés',
    'Decimais:' => 'Décimales :',
    'Decreto Presidencial n.º 71/25 — Sistema de Faturação Eletrónica' => 'Décret présidentiel n° 71/25 — Système de facturation électronique',
    'Definido pela legislação angolana' => 'Défini par la législation angolaise',
    'Definir como série padrão' => 'Définir comme série par défaut',
    'Demonstração de Resultados' => 'Compte de résultat',
    'Demonstração de resultados completa' => 'Compte de résultat complet',
    'Demonstração de resultados do período' => 'Compte de résultat de la période',
    'Desconto Máximo Permitido (%)' => 'Remise maximale autorisée (%)',
    'Descrição (opcional)' => 'Description (facultatif)',
    'Descrição adicional (opcional)' => 'Description supplémentaire (facultatif)',
    'Descrição da série...' => 'Description de la série...',
    'Desembaraçado' => 'Dédouané',
    'Desembaraço Pendente' => 'Dédouanement en attente',
    'Desempenho de vendas por utilizador (exclui canceladas/creditadas)' => 'Performance des ventes par utilisateur (hors annulées/avoirs)',
    'Despesas operacionais não modeladas (incluir manualmente na contabilidade)' => 'Charges d\'exploitation non modélisées (à inclure manuellement en comptabilité)',
    'Detalhe' => 'Détail',
    'Detalhe por Serviço' => 'Détail par service',
    'Dias' => 'Jours',
    'Dias de Alerta (antes da validade)' => 'Jours d\'alerte (avant péremption)',
    'Dica' => 'Astuce',
    'Distribuição' => 'Répartition',
    'Doc. motorista' => 'Doc. chauffeur',
    'Docs' => 'Docs',
    'Documento, artigo ou pessoa...' => 'Document, article ou personne...',
    'Documento Conforme AGT' => 'Document conforme AGT',
    'Documento não encontrado' => 'Document introuvable',
    'Documento não fiscal; não é enviado à AGT.' => 'Document non fiscal ; il n\'est pas transmis à l\'AGT.',
    'Documento Rectificado' => 'Document rectifié',
    'Documento reenviado com sucesso!' => 'Document renvoyé avec succès !',
    'Documentos de transporte de mercadorias (GT / GR)' => 'Documents de transport de marchandises (GT / GR)',
    'Documentos enviados, validados ou rejeitados pela AGT' => 'Documents envoyés, validés ou rejetés par l\'AGT',
    'Documento validado para conformidade AGT!' => 'Document validé pour la conformité AGT !',
    'DS.120 §4.6: A=Aberta, U=Em utilização, F=Fechada' => 'DS.120 §4.6 : A=Ouverte, U=En utilisation, F=Fermée',
    'Débito' => 'Débit',
    'Eliminar Adiantamento?' => 'Supprimer l\'acompte ?',
    'Eliminar Série?' => 'Supprimer la série ?',
    'Emails (CSV)' => 'E-mails (CSV)',
    'Emissão' => 'Émission',
    'Emitido por:' => 'Émis par :',
    'Empresa activa:' => 'Entreprise active :',
    'Empresas diferentes.' => 'Entreprises différentes.',
    'Em Trânsito' => 'En transit',
    'Entradas' => 'Entrées',
    'entre armazéns' => 'entre entrepôts',
    'Enviar documentos automaticamente à AGT' => 'Envoyer les documents automatiquement à l\'AGT',
    'Erro: :detalhe' => 'Erreur : :detalhe',
    'Erro ao abrir modal: :detalhe' => 'Erreur à l\'ouverture de la fenêtre : :detalhe',
    'Erro ao anular: :detalhe' => 'Erreur lors de l\'annulation : :detalhe',
    'Erro ao atualizar fatura: :detalhe' => 'Erreur lors de la mise à jour de la facture : :detalhe',
    'Erro ao converter: :detalhe' => 'Erreur lors de la conversion : :detalhe',
    'Erro ao eliminar série: :detalhe' => 'Erreur lors de la suppression de la série : :detalhe',
    'Erro ao gerar SAFT: :detalhe' => 'Erreur lors de la génération du SAFT : :detalhe',
    'Erro ao limpar documentos: :detalhe' => 'Erreur lors de la suppression des documents : :detalhe',
    'Erro ao salvar fatura: :detalhe' => 'Erreur lors de l\'enregistrement de la facture : :detalhe',
    'Erro ao salvar proforma: :detalhe' => 'Erreur lors de l\'enregistrement de la proforma : :detalhe',
    'Erro de validação: :detalhe' => 'Erreur de validation : :detalhe',
    'Escopo' => 'Portée',
    'Esta ação não pode ser desfeita! Todos os dados relacionados serão permanentemente eliminados.'
        => 'Cette action est irréversible ! Toutes les données liées seront définitivement supprimées.',
    'Estabelecimento' => 'Établissement',
    'Estabelecimento *' => 'Établissement *',
    'Esta chave é <strong>gerada e emitida pela AGT</strong> e está disponível no <a href=":portal" target="_blank" class="underline font-bold">Portal do Contribuinte</a>. É utilizada para assinar digitalmente cada documento (<code>jwsDocumentSignature</code>) e cada requisição (<code>jwsSignature</code>). <strong>Nunca partilhe esta chave.</strong>'
        => 'Cette clé est <strong>générée et délivrée par l\'AGT</strong> et disponible sur le <a href=":portal" target="_blank" class="underline font-bold">Portail du contribuable</a>. Elle sert à signer numériquement chaque document (<code>jwsDocumentSignature</code>) et chaque requête (<code>jwsSignature</code>). <strong>Ne partagez jamais cette clé.</strong>',
    'Estado:' => 'Statut :',
    'Estado AGT' => 'Statut AGT',
    'Estado SAFT' => 'Statut SAFT',
    'Esta fatura já está anulada.' => 'Cette facture est déjà annulée.',
    'Estas credenciais são globais do <strong>produtor de software</strong> — não do contribuinte.'
        => 'Ces identifiants appartiennent globalement au <strong>producteur du logiciel</strong> — pas au contribuable.',
    'Esta semana' => 'Cette semaine',
    'Este mês' => 'Ce mois-ci',
    'Estes campos só são usados ao registar a série na AGT (`SolicitarSerie`).' => 'Ces champs ne servent qu\'à l\'enregistrement de la série auprès de l\'AGT (`SolicitarSerie`).',
    'Estrutura do XML' => 'Structure du XML',
    'ETA (Prev. Chegada)' => 'ETA (arrivée prévue)',
    'EUR - Euro' => 'EUR - Euro',
    'Evolução dos Últimos 6 Meses' => 'Évolution des 6 derniers mois',
    'Ex.: 5001636863' => 'ex. : 5001636863',
    'Ex.: China' => 'ex. : Chine',
    'Ex.: FT A/2026/000001' => 'ex. : FT A/2026/000001',
    'Ex.: PO-2025-001' => 'ex. : PO-2025-001',
    'Ex.: Shanghai' => 'ex. : Shanghai',
    'Ex: IVA14' => 'ex. : IVA14',
    'Ex: IVA 14% Normal' => 'ex. : TVA 14 % normale',
    'Ex: LOTE-2025-001 ou deixe vazio para gerar automaticamente' => 'ex. : LOT-2025-001, ou laissez vide pour générer automatiquement',
    'Ex: Nº comprovante...' => 'ex. : n° de justificatif...',
    'Ex: Pagamento antecipado...' => 'ex. : paiement anticipé...',
    'Ex: Vendas Loja, Vendas Online' => 'ex. : Ventes boutique, Ventes en ligne',
    'Ex: Vendas Loja, Vendas Online...' => 'ex. : Ventes boutique, Ventes en ligne...',
    'Executar consulta' => 'Exécuter la requête',
    'Execute o seeder para criar os impostos de Angola' => 'Exécutez le seeder pour créer les taxes de l\'Angola',
    'Exemplo:' => 'Exemple :',
    'Exemplo: A, B, C, 01, 02, etc.' => 'Exemple : A, B, C, 01, 02, etc.',
    'Exemplo atual:' => 'Exemple actuel :',
    'Exigir cliente em todas as vendas' => 'Exiger un client sur toutes les ventes',
    'Exigir validação AGT antes de imprimir' => 'Exiger la validation AGT avant impression',
    'Exigir validação prévia' => 'Exiger une validation préalable',
    'Existem faturas com pagamento vencido' => 'Il existe des factures dont le paiement est échu',
    'Expira em 7 dias' => 'Expire dans 7 jours',
    'Expira em 30 dias' => 'Expire dans 30 jours',
    'Expirando em Breve' => 'Expire bientôt',
    'Exportar' => 'Exporter',
    'Exportar CSV' => 'Exporter en CSV',
    'Exportação em desenvolvimento...' => 'Export en cours de développement...',
    'Expressão (Art. 12º)' => 'Mention (art. 12)',
    'Factura anulada — o registo mantém-se por exigência fiscal' => 'Facture annulée — l\'enregistrement est conservé par obligation fiscale',
    'Factura de origem' => 'Facture d\'origine',
    'Facturação Electrónica AGT' => 'Facturation électronique AGT',
    'Falha na conexão' => 'Échec de la connexion',
    'Falhou.' => 'Échec.',
    'Fatura-Recibo POS (FR)' => 'Facture-reçu POS (FR)',
    'Fatura de Compra (FC)' => 'Facture d\'achat (FC)',
    'Fatura de compra anulada. O stock foi revertido.' => 'Facture d\'achat annulée. Le stock a été inversé.',
    'Fatura de origem (opcional)' => 'Facture d\'origine (facultatif)',
    'Faturas (FT)' => 'Factures (FT)',
    'Faturas:' => 'Factures :',
    'faturas com serviços' => 'factures avec services',
    'Faturas de Compra' => 'Factures d\'achat',
    'Faturas de Compra (FC)' => 'Factures d\'achat (FC)',
    'Faturas de compra pendentes' => 'Factures d\'achat en attente',
    'Faturas de compra por período' => 'Factures d\'achat par période',
    'Faturas de venda pendentes' => 'Factures de vente en attente',
    'Faturas e compras de fornecedores' => 'Factures et achats fournisseurs',
    'Faturas no Período' => 'Factures sur la période',
    'Faturas pendentes a fornecedores' => 'Factures en attente auprès des fournisseurs',
    'Faturas pendentes de clientes' => 'Factures en attente des clients',
    'Faturação → Séries de Documentos' => 'Facturation → Séries de documents',
    'FEPC — Pré-Comunicada' => 'FEPC — Pré-déclarée',
    'Ferramentas API' => 'Outils API',
    'FESF — Sem Facturação' => 'FESF — Sans facturation',
    'Fiabilidade' => 'Fiabilité',
    'Fiabilidade (25 pts):' => 'Fiabilité (25 pts) :',
    'Fiabilidade:' => 'Fiabilité :',
    'Filtrar por Tipo' => 'Filtrer par type',
    'Filtro' => 'Filtre',
    'Finalidade' => 'Finalité',
    'Fiscal & SAFT' => 'Fiscal et SAFT',
    'FOB + Frete + Seguro' => 'FOB + fret + assurance',
    'Formato:' => 'Format :',
    'Formato AGT Angola' => 'Format AGT Angola',
    'Formato de Números e Decimais' => 'Format des nombres et décimales',
    'Formato PEM, RSA mínimo 2048 bits. Armazenada localmente no servidor (não na BD).' => 'Format PEM, RSA 2048 bits minimum. Stockée localement sur le serveur (pas en base).',
    'Fornecedor *' => 'Fournisseur *',
    'Fornecedor criado com sucesso: :detalhe' => 'Fournisseur créé avec succès : :detalhe',
    'Fornecedor selecionado: :detalhe' => 'Fournisseur sélectionné : :detalhe',
    'FR = Fatura-Recibo (fixo)' => 'FR = Facture-reçu (fixe)',
    'FR A' => 'FR A',
    'Frequência (20 pts):' => 'Fréquence (20 pts) :',
    'Frete' => 'Fret',
    'FT, FR, PR, RC, NC, ND, FC, AD' => 'FT, FR, PR, RC, NC, ND, FC, AD',
    'FT A 2025/000001' => 'FT A 2025/000001',
    'Gerador de Documentos AGT Angola' => 'Générateur de documents AGT Angola',
    'Gerar Documentos' => 'Générer des documents',
    'Gerar e Baixar SAFT-AO' => 'Générer et télécharger le SAFT-AO',
    'Gerar PDF' => 'Générer le PDF',
    'Gere documentos de teste conforme Decreto Presidencial 312/18' => 'Générez des documents de test conformes au décret présidentiel 312/18',
    'Gerir impostos' => 'Gérer les taxes',
    'Gerir Impostos' => 'Gérer les taxes',
    'Gestão completa do processo de importação - Angola' => 'Gestion complète du processus d\'importation - Angola',
    'Gestão de Impostos' => 'Gestion des taxes',
    'Gestão de Impostos (IVA)' => 'Gestion des taxes (TVA)',
    'Gestão de Séries de Documentos' => 'Gestion des séries de documents',
    'Global' => 'Global',
    'Guardar configuração' => 'Enregistrer la configuration',
    'Guardar Configurações' => 'Enregistrer les paramètres',
    'Guia de Remessa' => 'Bon de livraison',
    'Guia de Transporte' => 'Bon de transport',
    'Guia de Transporte (GT)' => 'Bon de transport (GT)',
    'Guias de Transporte (GT)' => 'Bons de transport (GT)',
    'Guias de Transporte / Remessa' => 'Bons de transport / livraison',
    'Hash' => 'Hash',
    'Hash presente:' => 'Hash présent :',
    'Hash SAFT' => 'Hash SAFT',
    'Histórico de Submissões FE' => 'Historique des soumissions FE',
    'Hoje' => 'Aujourd\'hui',
    'Homologação' => 'Homologation',
    'Homologação (sandbox)' => 'Homologation (bac à sable)',
    'Importante' => 'Important',
    'Importações de Mercadorias' => 'Importations de marchandises',
    'Imposto padrão' => 'Taxe par défaut',
    'Imposto Padrão (IVA)' => 'Taxe par défaut (TVA)',
    'Impostos' => 'Taxes',
    'Impostos Disponíveis' => 'Taxes disponibles',
    'Impostos e Retenções' => 'Taxes et retenues',
    'Impressão' => 'Impression',
    'Imprimir automaticamente após salvar' => 'Imprimer automatiquement après enregistrement',
    'Imprimir automaticamente após venda' => 'Imprimer automatiquement après la vente',
    'Inactivo' => 'Inactif',
    'Inactivos' => 'Inactifs',
    'Incluir ano no formato (FT A/2025/000001)' => 'Inclure l\'année dans le format (FT A/2025/000001)',
    'Indicador' => 'Indicateur',
    'Informações do Adiantamento' => 'Informations sur l\'acompte',
    'Informações do Fornecedor' => 'Informations du fournisseur',
    'Inspeção Alfandegária' => 'Inspection douanière',
    'instalada' => 'installée',
    'Instale primeiro o par RSA de Produção do Portal do Contribuinte. Sem ele nenhum documento é assinado.'
        => 'Installez d\'abord la paire RSA de Production issue du Portail du contribuable. Sans elle, aucun document n\'est signé.',
    'Internacional - 20,000.00' => 'International - 20,000.00',
    'inventário corrigido' => 'inventaire corrigé',
    'ISE - Isento' => 'ISE - Exonéré',
    'IVA Dedutível (Compras)' => 'TVA déductible (achats)',
    'IVA Dedutível por Taxa' => 'TVA déductible par taux',
    'IVA Liquidado (Vendas)' => 'TVA collectée (ventes)',
    'IVA liquidado, dedutível e a entregar' => 'TVA collectée, déductible et à reverser',
    'IVA liquidado, dedutível e a pagar' => 'TVA collectée, déductible et à payer',
    'IVA Liquidado por Taxa' => 'TVA collectée par taux',
    'Jan–15Dez: ano corrente. Após 15Dez: corrente ou seguinte.' => 'Jan–15 déc. : année en cours. Après le 15 déc. : en cours ou suivante.',
    'Já Expirados' => 'Déjà périmés',
    'Já Pago' => 'Déjà payé',
    'Já é este o ambiente activo.' => 'C\'est déjà l\'environnement actif.',
    'Limite' => 'Limite',
    'Limpar Todos os Documentos' => 'Effacer tous les documents',
    'Links Rápidos' => 'Liens rapides',
    'Liquidado − Dedutível' => 'Collectée − déductible',
    'Lista de emails (separados por vírgula) que recebem notificação quando uma submissão à AGT é <strong>rejeitada</strong> (resultCode 2) ou contém <strong>erros parciais</strong> (resultCode 1). Se vazio, é usado o fallback dos utilizadores com permissão <code class="bg-amber-100 px-1 rounded">invoicing.agt.view</code>.'
        => 'Liste d\'e-mails (séparés par des virgules) notifiés lorsqu\'une soumission à l\'AGT est <strong>rejetée</strong> (resultCode 2) ou contient des <strong>erreurs partielles</strong> (resultCode 1). Si vide, le repli porte sur les utilisateurs ayant la permission <code class="bg-amber-100 px-1 rounded">invoicing.agt.view</code>.',
    'Lista de Faturas de Compra' => 'Liste des factures d\'achat',
    'ListarFacturas — documentos RECEBIDOS (empresa como adquirente)' => 'ListarFacturas — documents REÇUS (entreprise en tant qu\'acquéreur)',
    'Local de carga' => 'Lieu de chargement',
    'Local de descarga' => 'Lieu de déchargement',
    'Logs' => 'Journaux',
    'Logs de Comunicação' => 'Journaux de communication',
    'Logística & Transporte' => 'Logistique et transport',
    'Lote/Validade' => 'Lot/Péremption',
    'Luanda' => 'Luanda',
    'Lucro' => 'Bénéfice',
    'Lucro/prejuízo por produto vendido' => 'Bénéfice/perte par produit vendu',
    'Lucro e margem por produto' => 'Bénéfice et marge par produit',
    'Lucro Unit.' => 'Bénéfice unit.',
    'Maior lucro' => 'Bénéfice le plus élevé',
    'Maior margem' => 'Marge la plus élevée',
    'Maior margem %' => 'Marge % la plus élevée',
    'Maior prejuízo' => 'Perte la plus élevée',
    'Maior receita' => 'Chiffre d\'affaires le plus élevé',
    'Maior rotação' => 'Rotation la plus élevée',
    'Mais vendidos' => 'Meilleures ventes',
    'Marcar como Conforme' => 'Marquer comme conforme',
    'Margem' => 'Marge',
    'Margem %' => 'Marge %',
    'Margem:' => 'Marge :',
    'Margem Média' => 'Marge moyenne',
    'Margem Negativa' => 'Marge négative',
    'Markup' => 'Markup',
    'Markup %' => 'Markup %',
    'Marque todos os itens do checklist antes de aprovar' => 'Cochez tous les éléments de la liste avant d\'approuver',
    'Marítimo' => 'Maritime',
    'Matrícula da viatura' => 'Immatriculation du véhicule',
    'MB Way' => 'MB Way',
    'Meio' => 'Mode',
    'Meio para cima (0,5+)' => 'Arrondi supérieur (0,5+)',
    'Menor margem %' => 'Marge % la plus faible',
    'Menor stock' => 'Stock le plus faible',
    'Mensagem AGT visível' => 'Message AGT visible',
    'Modo' => 'Mode',
    'Moeda:' => 'Devise :',
    'Moeda Padrão' => 'Devise par défaut',
    'Mostrar imagens dos produtos' => 'Afficher les images des produits',
    'Mostrar logótipo da empresa' => 'Afficher le logo de l\'entreprise',
    'Motorista' => 'Chauffeur',
];

foreach (['en' => $en, 'fr' => $fr] as $lingua => $novas) {
    $caminho = "{$raiz}/lang/{$lingua}.json";
    $dicionario = json_decode(file_get_contents($caminho), true) ?: [];

    $acrescentadas = 0;
    $conflitos = [];

    foreach ($novas as $pt => $traduzida) {
        if (isset($dicionario[$pt])) {
            if ($dicionario[$pt] !== $traduzida) {
                $conflitos[$pt] = [$dicionario[$pt], $traduzida];
            }
            continue;
        }

        $dicionario[$pt] = $traduzida;
        $acrescentadas++;
    }

    ksort($dicionario, SORT_NATURAL | SORT_FLAG_CASE);

    file_put_contents(
        $caminho,
        json_encode($dicionario, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . "\n"
    );

    printf("lang/%s.json: +%d (total %d)\n", $lingua, $acrescentadas, count($dicionario));

    foreach ($conflitos as $pt => [$antiga, $nova]) {
        printf("    conflito em \"%s\": tinha \"%s\"\n", mb_substr($pt, 0, 40), mb_substr($antiga, 0, 40));
    }
}
